In [5]:
import numpy as np

In [6]:
# bigger screen
pixels_actual_view = np.array([1920, 1058])

In [7]:
# pix_per_deg on bigger screen est at 35 (this is under)
pix_per_deg = 35
stim_size_pix = pix_per_deg*5

In [8]:
stim_prop = stim_size_pix/pixels_actual_view
stim_prop

array([0.09114583, 0.16540643])

In [9]:
# smaller screen

pixels_actual_view = np.array([1438, 680])
cm_actual_view = np.array([28.5, 12.5])
pixels_actual_view / cm_actual_view

array([50.45614035, 54.4       ])

In [10]:
# pix_per_deg on smaller screen est at 50 (this is about right)
pix_per_deg = 50
stim_size_pix = pix_per_deg*5

In [11]:
stim_prop = stim_size_pix/pixels_actual_view
stim_prop

array([0.17385257, 0.36764706])