In [2]:
f ='/user_data/mmhender/featsynth/expt_design/expt3/trial_info_counterbal1_randorder0.csv'
import pandas as pd
import numpy as np

d = pd.read_csv(f)

In [4]:
np.unique(d['trial_in_run'])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [5]:
np.unique(d['run_number'])

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [6]:
d

trial_num_overall  run_number  trial_in_run  image_set_num  \
0                    0         0.0             0            0.0   
1                    1         0.0             1            0.0   
2                    2         0.0             2            0.0   
3                    3         0.0             3            0.0   
4                    4         0.0             4            0.0   
..                 ...         ...           ...            ...   
635                635        15.0            35            0.0   
636                636        15.0            36            0.0   
637                637        15.0            37            0.0   
638                638        15.0            38            0.0   
639                639        15.0            39            0.0   

     random_order_number  categ_ind  concept_ind          super_name  \
0                    0.0        5.0          6.0  musical_instrument   
1                    0.0        5.0          3.0  musical_instrument   
2                    0.0        3.0          1.0             dessert   
3                    0.0        5.0          4.0  musical_instrument   
4                    0.0        1.0          5.0           vegetable   
..                   ...        ...          ...                 ...   
635                  0.0        5.0          4.0  musical_instrument   
636                  0.0        5.0          6.0  musical_instrument   
637                  0.0        5.0          4.0  musical_instrument   
638                  0.0        5.0          3.0  musical_instrument   
639                  0.0        5.0          3.0  musical_instrument   

    basic_name  ex_num  ...  image_type                            image_name  \
0     clarinet     1.0  ...        orig                 clarinet_02n/orig.png   
1         drum     3.0  ...       pool1      drum_04s/scramble_upto_pool1.png   
2       muffin     1.0  ...        orig                   muffin_02n/orig.png   
3       violin     7.0  ...       pool3    violin_08s/scramble_upto_pool3.png   
4      lettuce     1.0  ...        orig                  lettuce_02n/orig.png   
..         ...     ...  ...         ...                                   ...   
635     violin     0.0  ...        orig                   violin_01b/orig.png   
636   clarinet     6.0  ...       pool3  clarinet_07n/scramble_upto_pool3.png   
637     violin     8.0  ...       pool4    violin_09s/scramble_upto_pool4.png   
638       drum     0.0  ...        orig                     drum_01b/orig.png   
639       drum     6.0  ...       pool3      drum_07s/scramble_upto_pool3.png   

                                           dropbox_url cue_level_num  \
0    https://dl.dropboxusercontent.com/scl/fi/z2dyd...           1.0   
1    https://dl.dropboxusercontent.com/scl/fi/vj7v2...           1.0   
2    https://dl.dropboxusercontent.com/scl/fi/7rkv1...           1.0   
3    https://dl.dropboxusercontent.com/scl/fi/bjo47...           1.0   
4    https://dl.dropboxusercontent.com/scl/fi/90k1l...           1.0   
..                                                 ...           ...   
635  https://dl.dropboxusercontent.com/scl/fi/n43zv...           0.0   
636  https://dl.dropboxusercontent.com/scl/fi/u1b7y...           0.0   
637  https://dl.dropboxusercontent.com/scl/fi/zsml3...           0.0   
638  https://dl.dropboxusercontent.com/scl/fi/jn863...           0.0   
639  https://dl.dropboxusercontent.com/scl/fi/4q8og...           0.0   

     cue_level            cue_name distractor_name  left_name  \
0        super  musical_instrument            tool       tool   
1        super  musical_instrument           fruit      fruit   
2        super             dessert       furniture    dessert   
3        super  musical_instrument          insect     insect   
4        super           vegetable         dessert  vegetable   
..         ...                 ...             ...        ...   
635      basic              violin        

In [9]:
d.keys()

Index(['trial_num_overall', 'run_number', 'trial_in_run', 'image_set_num',
       'random_order_number', 'categ_ind', 'concept_ind', 'super_name',
       'basic_name', 'ex_num', 'image_type_num', 'image_type', 'image_name',
       'dropbox_url', 'cue_level_num', 'cue_level', 'cue_name',
       'distractor_name', 'left_name', 'right_name', 'correct_resp'],
      dtype='object')

In [15]:
# d[d['cue_level']=='basic']
inds = np.array(d['run_number'])==1.0

np.unique(np.array(d.iloc[inds]['basic_name']), return_counts=True)

(array(['brownie', 'candy', 'cookie', 'cupcake', 'milkshake', 'muffin',
        'pastry', 'pie'], dtype=object),
 array([5, 5, 5, 5, 5, 5, 5, 5]))