In [1]:
import os
import sys
import numpy as np
import pandas as pd
import scipy.io
import PIL.Image


things_stim_path = '/user_data/mmhender/stimuli/things/'
ecoset_path = '/lab_data/tarrlab/common/datasets/Ecoset/'
ecoset_info_path = '/user_data/mmhender/stimuli/ecoset_info/'


In [1]:
import proc_ecoset_categs 
proc_ecoset_categs.get_ecoset_files_includeperson()

beetle: there are 4200 images in total after QC, choosing 500
beetle: 0.04 of selected images have person
bee: there are 4019 images in total after QC, choosing 500
bee: 0.01 of selected images have person
butterfly: there are 3954 images in total after QC, choosing 500
butterfly: 0.02 of selected images have person
grasshopper: there are 3682 images in total after QC, choosing 500
grasshopper: 0.04 of selected images have person
caterpillar: there are 3621 images in total after QC, choosing 500
caterpillar: 0.03 of selected images have person
ant: there are 3498 images in total after QC, choosing 500
ant: 0.02 of selected images have person
moth: there are 3133 images in total after QC, choosing 500
moth: 0.03 of selected images have person
mosquito: there are 1953 images in total after QC, choosing 500
mosquito: 0.02 of selected images have person
pea: there are 3403 images in total after QC, choosing 500
pea: 0.05 of selected images have person
corn: there are 3217 images in total a

In [9]:
import numpy as np

efiles = np.load('/user_data/mmhender/stimuli/ecoset_info/ecoset_files_includeperson.npy', allow_pickle=True).item()

efiles['ukulele']['has_person']

array([0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0.,
       0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1.,
       0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0.,
       1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1.,
       1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 1.

In [8]:
import numpy as np

efiles = np.load('/user_data/mmhender/stimuli/ecoset_info/ecoset_files_use.npy', allow_pickle=True).item()

efiles['ukulele']['has_person']

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [1]:
import proc_ecoset_categs 

proc_ecoset_categs.choose_ecoset_categs()

0 insect
['beetle' 'bee' 'butterfly' 'grasshopper' 'caterpillar' 'ant' 'moth'
 'mosquito']
[4288 4105 4035 3766 3702 3572 3191 2014]
1 vegetable
['pea' 'corn' 'pumpkin' 'onion' 'cabbage' 'lettuce' 'beet' 'asparagus']
[3490 3296 3118 3101 3073 3039 2566 2239]
2 fruit
['grape' 'cherry' 'raspberry' 'apple' 'pear' 'banana' 'pomegranate'
 'coconut']
[3169 2989 2781 2726 2674 2645 2307 2298]
3 dessert
['candy' 'muffin' 'pastry' 'cupcake' 'cookie' 'pie' 'milkshake' 'brownie']
[3588 3028 2096 1068  947  896  894  819]
4 tool
['pencil' 'knife' 'axe' 'broom' 'hammer' 'shovel' 'spoon' 'scissors']
[3116 2966 2647 2307 2041 1936 1816 1748]
5 musical instrument
['bell' 'guitar' 'piano' 'drum' 'violin' 'mandolin' 'clarinet' 'ukulele']
[3943 3651 3375 3256 2883 1573 1442 1267]
6 furniture
['table' 'bench' 'couch' 'television' 'bed' 'chair' 'refrigerator' 'lamp']
[4028 3808 3708 3507 3365 3114 2968 2481]
7 vehicle
['ship' 'train' 'airplane' 'truck' 'car' 'bus' 'motorcycle' 'canoe']
[4051 3998 3867 3758

In [5]:
# this is where we are choosing 8 basic-level categories from each superordinate category

# load names of all categories in ecoset dataset
ecoset_folders = np.load(os.path.join(ecoset_info_path, 'ecoset_names.npy'), \
                         allow_pickle=True).item()

superord_use, basic_names_each = proc_ecoset_categs.choose_ecoset_categs_step1()

counts_each = np.array([len(bnames) for bnames in basic_names_each])

# will subsample 8 basic from each superord
n_basic_min = 8;
assert(np.all(counts_each>=n_basic_min))

# list of all files in each category
fn = os.path.join(ecoset_info_path, 'ecoset_file_info.npy')
efiles = np.load(fn, allow_pickle=True).item()

# going to exclude a few categories, to help prevent ambiguity. 
# these are all similar to another category in their superordinate
exclude = ['wasp', 'razor', 'melon']

# choose whichever basic categories have the most images available
basic_names_subsample = []
for si in range(len(superord_use)):
    bnames = np.array(basic_names_each[si])
    bnames = bnames[~np.isin(bnames, exclude)]

    basic_counts = np.array([efiles[bname]['good_ims'] for bname in bnames])
    print(si, superord_use[si])
    print(basic_names_each[si])
    print(basic_counts)
    inds_use = np.flipud(np.argsort(basic_counts))[0:n_basic_min]
    bnames_use = np.array(basic_names_each[si])[inds_use]
    print(bnames_use)
    print(basic_counts[inds_use])
    basic_names_subsample += [bnames_use]


0 insect
['ant' 'bee' 'beetle' 'butterfly' 'caterpillar' 'cockroach' 'dragonfly'
 'grasshopper' 'mosquito' 'moth' 'wasp']
[3572 4105 4288 4035 3702 1696 1915 3766 2014 3191]
['beetle' 'bee' 'butterfly' 'grasshopper' 'caterpillar' 'ant' 'moth'
 'mosquito']
[4288 4105 4035 3766 3702 3572 3191 2014]
1 vegetable
['artichoke' 'asparagus' 'beet' 'broccoli' 'cabbage' 'carrot'
 'cauliflower' 'celery' 'corn' 'cucumber' 'eggplant' 'garlic' 'kale'
 'leek' 'lettuce' 'onion' 'parsley' 'pea' 'potato' 'pumpkin' 'radish'
 'rhubarb' 'scallion' 'spinach' 'zucchini']
[1717 2239 2566 1940 3073 2041 2021  925 3296 1347 1917 1536 1672  817
 3039 3101 2002 3490  992 3118 2251 1360 1349 1321 1233]
['pea' 'corn' 'pumpkin' 'onion' 'cabbage' 'lettuce' 'beet' 'radish']
[3490 3296 3118 3101 3073 3039 2566 2251]
2 fruit
['apple' 'banana' 'blackberry' 'blueberry' 'cherry' 'coconut' 'cranberry'
 'fig' 'grape' 'grapefruit' 'lemon' 'lime' 'mango' 'melon' 'papaya'
 'peach' 'pear' 'pineapple' 'plum' 'pomegranate' 'raspbe

In [2]:
# load the list of all concepts (basic-level) in THINGS dataset
filename = os.path.join(things_stim_path,'things_concepts.tsv')
df = pd.read_csv(filename, sep='\t')
things_names = np.array(df['Word'])

# load names of all categories (superord) in THINGS dataset
info_folder = os.path.join(things_stim_path,'27 higher-level categories')
categ_names = scipy.io.loadmat(os.path.join(info_folder, 'categories.mat'))['categories'][0]
categ_names = np.array([categ_names[ii][0] for ii in range(len(categ_names))])

# correspondence between things concepts (basic) and categories (superord)
# this matrix goes [basic x super]
dat = scipy.io.loadmat(os.path.join(info_folder, 'category_mat_manual.mat'))
cmat = dat['category_mat_manual']
cmat_use = cmat==1


In [8]:
# skip any that are the same name as superordinate, because that won't make sense
things_inds_skip = np.isin(things_names, categ_names) 

# removing any duplicate concept names here (these are ambiguous meaning words like bat)
un, counts = np.unique(things_names, return_counts=True)
duplicate_conc = un[counts>1]
duplicate_conc_inds = [conc in duplicate_conc for conc in things_names]
things_inds_skip = things_inds_skip | duplicate_conc_inds

# skip some other ones that I found confusing/uncommon 
#(cheese was included as dessert, avocado was fruit)
conc_skip = ['earwig', 'cheese', 'avocado', 'anvil', 'okra']
things_inds_skip = things_inds_skip | np.isin(things_names, conc_skip)

things_names_skip = things_names[things_inds_skip]

# load names of all categories in ecoset dataset
ecoset_folders = np.load(os.path.join(ecoset_info_path, 'ecoset_names.npy'), \
                         allow_pickle=True).item()
ecoset_names = np.array(list(ecoset_folders.keys()))

# get overlap
is_in_ecoset = [np.any([(t==e) for e in ecoset_names]) for t in things_names]

# this is the list of 8 superord categories to use here
# chosen based on which ones had at least 8 basic-level members in ecoset, 
# and also trying to minimize overlap between categories. 
superord_use = categ_names

superord_inds_use = np.array([np.where(categ_names==superord)[0][0] for superord in superord_use])

# going to exclude any basic-level that occur in multiple superord categ
used_once = np.sum(cmat_use[:,superord_inds_use], axis=1)==1

# inds_each = [(cmat_use[:,ci] & is_in_ecoset & ~things_inds_skip & used_once) \
#                         for ci in superord_inds_use]
inds_each = [(cmat_use[:,ci] & is_in_ecoset & ~things_inds_skip) \
                        for ci in superord_inds_use]

counts_each = np.array([np.sum(inds) for inds in inds_each])

# this is the resulting list of basic categ in each superord categ.
# there are still too many here so we will further pare down based on file counts
basic_names_each = [things_names[inds] for inds in inds_each]


In [9]:
for si, sname in enumerate(superord_use):
    print(sname)
    print(basic_names_each[si])

animal
['alligator' 'ant' 'anteater' 'antelope' 'barnacle' 'bear' 'beaver' 'bee'
 'beetle' 'bison' 'boar' 'butterfly' 'camel' 'cat' 'caterpillar' 'cheetah'
 'chinchilla' 'chipmunk' 'cockroach' 'cow' 'deer' 'dog' 'dolphin' 'donkey'
 'dragonfly' 'elephant' 'ferret' 'fish' 'frog' 'giraffe' 'goat'
 'grasshopper' 'groundhog' 'hamster' 'hedgehog' 'horse' 'iguana'
 'jellyfish' 'kangaroo' 'koala' 'leopard' 'lion' 'lizard' 'llama'
 'lobster' 'manatee' 'monkey' 'moose' 'mosquito' 'moth' 'octopus' 'otter'
 'oyster' 'panda' 'pig' 'platypus' 'porcupine' 'rabbit' 'raccoon' 'rat'
 'scorpion' 'sheep' 'shrimp' 'skunk' 'sloth' 'snail' 'snake' 'spider'
 'squirrel' 'starfish' 'tadpole' 'tiger' 'turtle' 'walrus' 'warthog'
 'wasp' 'weasel' 'whale' 'wolf' 'worm' 'zebra']
bird
[]
body part
[]
clothing
['crown']
clothing accessory
['earring']
container
['ashtray' 'backpack' 'bag' 'barrel' 'basket' 'beaker' 'birdcage' 'bottle'
 'bowl' 'breadbox' 'bucket' 'closet' 'coffin' 'crate' 'cup' 'dustpan'
 'glass' 'jar' 

In [7]:
np.intersect1d(ecoset_names, things_names)

array(['acorn', 'airplane', 'alligator', 'aloe', 'altar', 'anchor', 'ant',
       'anteater', 'antelope', 'antenna', 'anvil', 'apple', 'artichoke',
       'ashtray', 'asparagus', 'avocado', 'axe', 'backpack', 'bag',
       'bagel', 'ball', 'balloon', 'bamboo', 'banana', 'bandage',
       'banner', 'barnacle', 'barrel', 'basket', 'battery', 'beaker',
       'bean', 'bear', 'beaver', 'bed', 'bee', 'beet', 'beetle', 'bell',
       'bench', 'bib', 'binoculars', 'bird', 'birdcage', 'birdhouse',
       'bison', 'blackberry', 'blanket', 'blender', 'blimp', 'blowtorch',
       'blueberry', 'boar', 'boat', 'bolt', 'book', 'bottle', 'bowl',
       'bracelet', 'bread', 'breadbox', 'broccoli', 'broom', 'brownie',
       'bubble', 'bucket', 'bulldozer', 'bullet', 'bun', 'burner',
       'burrito', 'bus', 'butterfly', 'cabbage', 'cactus', 'cake',
       'calculator', 'camcorder', 'camel', 'camera', 'candelabra',
       'candle', 'candy', 'cane', 'cannon', 'canoe', 'car', 'carousel',
       'carrot',

In [1]:
import proc_ecoset_categs

proc_ecoset_categs.get_ecoset_files_good()

beetle: 0.03 of images have person
beetle: there are 4068 images in total after QC, choosing 500
bee: 0.01 of images have person
bee: there are 3960 images in total after QC, choosing 500
butterfly: 0.01 of images have person
butterfly: there are 3904 images in total after QC, choosing 500
grasshopper: 0.03 of images have person
grasshopper: there are 3570 images in total after QC, choosing 500
caterpillar: 0.03 of images have person
caterpillar: there are 3513 images in total after QC, choosing 500
ant: 0.01 of images have person
ant: there are 3449 images in total after QC, choosing 500
moth: 0.02 of images have person
moth: there are 3059 images in total after QC, choosing 500
mosquito: 0.02 of images have person
mosquito: there are 1908 images in total after QC, choosing 500
pea: 0.06 of images have person
pea: there are 3192 images in total after QC, choosing 500
corn: 0.16 of images have person
corn: there are 2707 images in total after QC, choosing 500
pumpkin: 0.18 of images ha