In [1]:
import sys, os
import numpy as np
import time
from sklearn import decomposition
import pandas as pd
import torch
import PIL

project_root = '/user_data/mmhender/featsynth/'
texture_synth_root = os.path.join(project_root, 'texture_synthesis')

# this is in the 'texture_synthesis' folder
import utilities
import model_spatial

# from image_analysis import extract_resnet_features
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
  

cuda


In [9]:
imfn = df['image_filename'][0]

In [28]:
target_image = utilities.preprocess_image(
                    utilities.load_image(imfn)
                )

In [29]:
target_image

tensor([[[[ 36.0610,  36.0610,  34.0610,  ..., -36.9390, -38.9390, -41.9390],
          [ 32.0610,  32.0610,  29.0610,  ..., -36.9390, -37.9390, -40.9390],
          [ 30.0610,  28.0610,  25.0610,  ..., -34.9390, -36.9390, -39.9390],
          ...,
          [-72.9390, -70.9390, -67.9390,  ..., -54.9390, -59.9390, -59.9390],
          [-70.9390, -67.9390, -67.9390,  ..., -55.9390, -61.9390, -61.9390],
          [-71.9390, -71.9390, -74.9390,  ..., -57.9390, -64.9390, -65.9390]],

         [[ 64.2210,  63.2210,  60.2210,  ...,  11.2210,   8.2210,   5.2210],
          [ 63.2210,  61.2210,  58.2210,  ...,  10.2210,   9.2210,   6.2210],
          [ 62.2210,  59.2210,  56.2210,  ...,  11.2210,   9.2210,   6.2210],
          ...,
          [-33.7790, -26.7790, -15.7790,  ..., -62.7790, -66.7790, -66.7790],
          [-30.7790, -22.7790, -17.7790,  ..., -63.7790, -69.7790, -69.7790],
          [-31.7790, -26.7790, -26.7790,  ..., -63.7790, -69.7790, -71.7790]],

         [[ 96.3200,  93.3200,

In [20]:
image_data[0]

array([[[220, 217, 213, ..., 104, 101,  98],
        [218, 215, 210, ..., 103, 102,  99],
        [216, 213, 208, ..., 105, 103,  99],
        ...,
        [ 56,  62,  71, ...,  48,  43,  42],
        [ 57,  65,  69, ...,  46,  41,  41],
        [ 57,  61,  60, ...,  44,  40,  38]],

       [[181, 180, 177, ..., 128, 125, 122],
        [180, 178, 175, ..., 127, 126, 123],
        [179, 176, 173, ..., 128, 126, 123],
        ...,
        [ 83,  90, 101, ...,  54,  50,  50],
        [ 86,  94,  99, ...,  53,  47,  47],
        [ 85,  90,  90, ...,  53,  47,  45]],

       [[140, 140, 138, ...,  67,  65,  62],
        [136, 136, 133, ...,  67,  66,  63],
        [134, 132, 129, ...,  69,  67,  64],
        ...,
        [ 31,  33,  36, ...,  49,  44,  44],
        [ 33,  36,  36, ...,  48,  42,  42],
        [ 32,  32,  29, ...,  46,  39,  38]]])

In [25]:
import PIL


In [27]:
im = PIL.Image.fromarray(np.moveaxis(image_data[ii].astype(np.uint8),[0],[2]))

target_image = utilities.preprocess_image(im)
target_image

tensor([[[[ 36.0610,  36.0610,  34.0610,  ..., -36.9390, -38.9390, -41.9390],
          [ 32.0610,  32.0610,  29.0610,  ..., -36.9390, -37.9390, -40.9390],
          [ 30.0610,  28.0610,  25.0610,  ..., -34.9390, -36.9390, -39.9390],
          ...,
          [-72.9390, -70.9390, -67.9390,  ..., -54.9390, -59.9390, -59.9390],
          [-70.9390, -67.9390, -67.9390,  ..., -55.9390, -61.9390, -61.9390],
          [-71.9390, -71.9390, -74.9390,  ..., -57.9390, -64.9390, -65.9390]],

         [[ 64.2210,  63.2210,  60.2210,  ...,  11.2210,   8.2210,   5.2210],
          [ 63.2210,  61.2210,  58.2210,  ...,  10.2210,   9.2210,   6.2210],
          [ 62.2210,  59.2210,  56.2210,  ...,  11.2210,   9.2210,   6.2210],
          ...,
          [-33.7790, -26.7790, -15.7790,  ..., -62.7790, -66.7790, -66.7790],
          [-30.7790, -22.7790, -17.7790,  ..., -63.7790, -69.7790, -69.7790],
          [-31.7790, -26.7790, -26.7790,  ..., -63.7790, -69.7790, -71.7790]],

         [[ 96.3200,  93.3200,

In [2]:
debug=True
image_set_name = 'images_expt1_intactonly'

feat_path = os.path.join(project_root, 'features', 'gram_matrices')
    
if debug:
    feat_path = os.path.join(feat_path,'DEBUG')

if not os.path.exists(feat_path):
    os.makedirs(feat_path)

# load images to process
folder_images = os.path.join(project_root, 'features','raw')
image_data_filename = os.path.join(folder_images, '%s_preproc.npy'%(image_set_name))
print('loading images from %s'%image_data_filename)
image_data = np.load(image_data_filename)
n_images = image_data.shape[0]

# stuff about the model to get gram matrices from
layers_process = ['pool1','pool2','pool3','pool4']
            
model_path = os.path.join(texture_synth_root, 'models','VGG19_normalized_avg_pool_pytorch')


loading images from /user_data/mmhender/featsynth/features/raw/images_expt1_intactonly_preproc.npy


In [18]:

for ii in range(1):

    st = time.time()
    
    # get image into format the model is expecting
    im = PIL.Image.fromarray(np.moveaxis(image_data[ii].astype(np.uint8),[0],[2]))
    target_image = utilities.preprocess_image(im)

    elapsed = time.time() - st
    print('took %.5f s to preproc image for synthesis'%elapsed)

    net = model_spatial.Model(model_path, device, target_image, \
                                                      important_layers=layers_process, \
                                                      spatial_weights_list = None,\
                                                      do_sqrt = True)
    
    gram_mats = net.gram_loss_hook.target_gram_matrices

    for li, gm in enumerate(gram_mats):

        gram_features[li][ii,:] = gm.detach().cpu().numpy().ravel()

took 0.01102 s to preproc image for synthesis


In [19]:
[np.prod(gm.shape) for gm in gram_mats]

[4096, 16384, 65536, 262144]

In [10]:
target_grams = net.gram_loss_hook.target_gram_matrices
len(target_grams)

4