In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os, sys

sys.path.insert(0, '/user_data/mmhender/featsynth/code')

project_root = '/user_data/mmhender/featsynth/'
expt_name = 'expt2'
data_folder = os.path.join(project_root, 'online_data', expt_name)
preproc_folder = os.path.join(data_folder, 'preproc')
from utils import date_utils


In [2]:
from behav_preproc import preproc_expt2
preproc_expt2.preproc_all()

/user_data/mmhender/featsynth/online_data/expt2/data_exp_130731-v7/data_exp_130731-v7_task-sq8b.csv


/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:46: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  r = pd.read_csv(task_filename)


/user_data/mmhender/featsynth/online_data/expt2/data_exp_130731-v6/data_exp_130731-v6_task-sq8b.csv


/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:46: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  r = pd.read_csv(task_filename)


/user_data/mmhender/featsynth/online_data/expt2/data_exp_130731-v8/data_exp_130731-v8_task-sq8b.csv
fixing column name for date
/user_data/mmhender/featsynth/online_data/expt2/data_exp_130731-v5/data_exp_130731-v5_task-sq8b.csv


/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:46: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  r = pd.read_csv(task_filename)


5c3a518e0b5bb30001033afd
[100 100 100 100 100 100 100   0 100 100]
5c935d881754ba001b25697a
[100 100   0   0   0   0   0   0   0   0]
5ed5afc6e8229914710ada06
[100  48   0   0   0   0   0   0   0   0]
5f342a35aea7432daf29219d
[100   0   0   0   0   0   0   0   0   0]
6083a723155840ab8e6b985c
[100 100 100 100 100 100 100 100 100   0]
60f07d8c1de076bcea9e0d44
[100 100 100 100 100 100 100   0 100 100]
631c8e97db06f601f81bd82f
[13  0  0  0  0  0  0  0  0  0]
['63f6ad3b6678834c702ed506' '6320e37620d067c7d322246a'
 '63d80e0449b458dd5f8140be' '60c948db3f288a3058c67f98'
 '5f508a49e247cd1ff3485af3' '62827896d034545333f4610c'
 '5e0e1f62814bba56ea1a86dd' '5c8676deddda2d00012ad386'
 '6419cedec2078147e5682474' '5badcd276322c5000157c196'
 '64060f1213c5c70c63c18b96' '612fd3208d3decaf3ec80bcc'
 '63b0953847122ffebd8a5991' '5d254db8bb2e30001933fe36'
 '610cd5f2b38b2d1bffe55477' '63474e67a5fd298c6103c409'
 '5d67d4393fcbbc0019f3e1a4' '5f5aa60bef062519ff711fe6'
 '5a925ea389de8200013eb274' '5ed856ab1f4a23368

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:238: RuntimeWarning: Mean of empty slice
  acc = np.nanmean(run_acc).round(2)
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:239: RuntimeWarning: Mean of empty slice
  rt = np.nanmean(run_avg_rts).round(2)


saving to /user_data/mmhender/featsynth/online_data/expt2/preproc/all_sub_list.csv
saving to /user_data/mmhender/featsynth/online_data/expt2/preproc/complete_subs_only.csv

subject 0, id: 63f6ad3b6678834c702ed506
date = ['29/04/2023 09:52:57']
counterbalance cond: 1
random order number: 50
run accuracies:
[57. 46. 60. 49. 50. 51. 58. 61. 60. 51.]
run avg RTs:
[468.6 436.3 416.5 348.8 407.1 395.2 389.3 436.1 440.8 406.2]
num missed responses:
[1 1 0 0 0 2 0 0 0 0]
intact acc: 0.58
intact accuracy too low, skipping subject

subject 1, id: 6320e37620d067c7d322246a
date = ['29/04/2023 09:55:26']
counterbalance cond: 1
random order number: 40
run accuracies:
[57. 60. 63. 65. 74. 67. 58. 63. 72. 66.]
run avg RTs:
[593.2 485.2 493.3 456.3 433.7 442.4 431.1 417.7 447.8 417.2]
num missed responses:
[1 0 0 0 0 0 0 0 0 0]
intact acc: 0.83
final number of this subject: 1

subject 2, id: 63d80e0449b458dd5f8140be
date = ['29/04/2023 09:56:20']
counterbalance cond: 1
random order number: 11
run accur

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:432: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['which_cb'] = np.full(fill_value=which_cb, shape=[trial_data.shape[0],])
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:433: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:437: SettingWithCopyWarning: 
A value is trying to


subject 13, id: 5d254db8bb2e30001933fe36
date = ['02/05/2023 14:47:06']
counterbalance cond: 1
random order number: 38
run accuracies:
[66. 67. 70. 61. 73. 66. 66. 74. 68. 69.]
run avg RTs:
[747.  676.3 583.8 587.9 556.6 539.6 569.  553.  548.1 566.2]
num missed responses:
[0 0 0 0 0 0 0 0 0 0]
intact acc: 0.92
final number of this subject: 10

subject 14, id: 610cd5f2b38b2d1bffe55477
date = ['02/05/2023 14:58:51']
counterbalance cond: 1
random order number: 51
run accuracies:
[65. 64. 64. 66. 57. 59. 53. 66. 59. 63.]
run avg RTs:
[703.3 933.8 643.1 724.3 746.  639.6 598.6 653.1 582.9 591.6]
num missed responses:
[0 2 1 0 0 0 0 0 1 0]
intact acc: 0.78
final number of this subject: 11

subject 15, id: 63474e67a5fd298c6103c409
date = ['02/05/2023 15:01:43']
counterbalance cond: 1
random order number: 93
run accuracies:
[51. 63. 64. 65. 63. 56. 71. 74. 75. 60.]
run avg RTs:
[768.2 832.7 840.  822.7 757.4 786.1 712.4 722.1 720.9 668.9]
num missed responses:
[0 0 0 0 0 1 0 0 0 0]
intact ac

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:432: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['which_cb'] = np.full(fill_value=which_cb, shape=[trial_data.shape[0],])
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:433: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:437: SettingWithCopyWarning: 
A value is trying to


subject 19, id: 5ed856ab1f4a23368be98b1a
date = ['30/05/2023 10:59:04']
counterbalance cond: 1
random order number: 94
run accuracies:
[72. 71. 68. 80. 73. 75. 74. 74. 66. 65.]
run avg RTs:
[937.3 883.4 568.7 625.4 591.8 557.9 523.9 525.9 556.1 534.5]
num missed responses:
[0 0 0 1 0 0 0 0 0 0]
intact acc: 0.89
final number of this subject: 14

subject 20, id: 60f6ce6de6cf393bcde0c14d
date = ['30/05/2023 11:01:32']
counterbalance cond: 2
random order number: 21
run accuracies:
[68. 69. 63. 71. 69. 65. 62. 73. 60. 76.]
run avg RTs:
[922.3 835.7 674.8 770.5 745.7 742.2 751.8 696.4 657.5 694. ]
num missed responses:
[0 0 1 0 1 0 0 0 0 1]
intact acc: 0.89
final number of this subject: 15

subject 21, id: 5f4f070d58f7aa1540f27f0e
date = ['30/05/2023 11:06:00']
counterbalance cond: 1
random order number: 68
run accuracies:
[63. 59. 68. 63. 61. 66. 65. 66. 70. 62.]
run avg RTs:
[824.3 890.8 802.1 701.6 671.  638.5 648.6 678.  637.8 691.3]
num missed responses:
[0 1 1 1 1 0 0 0 0 0]
intact ac

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:432: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['which_cb'] = np.full(fill_value=which_cb, shape=[trial_data.shape[0],])
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:433: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:437: SettingWithCopyWarning: 
A value is trying to


subject 25, id: 6323709c1a757febe9fae00c
date = ['30/05/2023 11:16:26']
counterbalance cond: 1
random order number: 69
run accuracies:
[57. 64. 66. 60. 47. 57. 56. 52. 54. 59.]
run avg RTs:
[593.1 696.7 612.7 582.9 492.7 480.5 487.4 483.5 448.8 490.5]
num missed responses:
[0 1 0 4 0 0 0 0 1 0]
intact acc: 0.71
intact accuracy too low, skipping subject

subject 26, id: 61560db6a537f0c454b23db0
date = ['30/05/2023 11:19:10']
counterbalance cond: 1
random order number: 93
run accuracies:
[58. 71. 58. 75. 63. 59. 66. 65. 64. 61.]
run avg RTs:
[757.3 820.  812.5 756.3 780.7 745.5 731.1 840.4 801.2 750. ]
num missed responses:
[0 0 1 0 0 0 0 1 0 0]
intact acc: 0.90
final number of this subject: 19

subject 27, id: 5e5dba9e3d60470d71dde9ef
date = ['30/05/2023 11:21:46']
counterbalance cond: 2
random order number: 4
run accuracies:
[21. 74. 68. 70. 66. 69. 66. 63. 67. 68.]
run avg RTs:
[1145.6  930.6 1037.8  963.5 1003.   950.7 1055.4 1003.2  892.1  810. ]
num missed responses:
[76  0  0  0 

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:432: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['which_cb'] = np.full(fill_value=which_cb, shape=[trial_data.shape[0],])
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:433: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:437: SettingWithCopyWarning: 
A value is trying to


subject 29, id: 610840262cce4d0594be48d0
date = ['30/05/2023 11:25:05']
counterbalance cond: 1
random order number: 48
run accuracies:
[61. 65. 75. 54. 59. 67. 71. 71. 70. 66.]
run avg RTs:
[744.6 833.6 828.3 679.9 704.7 704.2 709.6 752.8 792.4 800.1]
num missed responses:
[ 0  0  0 11  0  0  0  0  0  0]
intact acc: 0.85
final number of this subject: 20

subject 30, id: 5e86447d220e2f26a21bb066
date = ['30/05/2023 11:25:23']
counterbalance cond: 2
random order number: 35
run accuracies:
[57. 73. 62. 68. 71. 61. 73. 60. 76. 76.]
run avg RTs:
[751.6 717.1 771.6 651.2 733.7 706.9 729.8 698.9 694.9 751.7]
num missed responses:
[0 0 3 0 0 2 0 2 0 0]
intact acc: 0.85
final number of this subject: 21

subject 31, id: 59c9c8da5535800001a8e434
date = ['30/05/2023 11:28:28']
counterbalance cond: 2
random order number: 75
run accuracies:
[67. 70. 68. 63. 70. 70. 72. 78. 79. 79.]
run avg RTs:
[554.8 583.8 571.8 592.5 602.4 588.6 648.3 607.6 636.8 616.5]
num missed responses:
[0 0 0 0 0 0 0 0 0 0]

#### Print good subjects

In [3]:
good_df = pd.read_csv(os.path.join(preproc_folder,'good_subs_only.csv'), index_col=0)

sort_order = date_utils.argsort_dates(np.array(good_df['Expt Start Time (PST)']))
good_df.iloc[sort_order]
good_df

Gorilla public ID  Survey Completion Code  \
0   6320e37620d067c7d322246a                     NaN   
1   63d80e0449b458dd5f8140be                     NaN   
2   5f508a49e247cd1ff3485af3                     NaN   
3   62827896d034545333f4610c                     NaN   
4   5e0e1f62814bba56ea1a86dd                     NaN   
5   5c8676deddda2d00012ad386                     NaN   
6   6419cedec2078147e5682474                     NaN   
7   5badcd276322c5000157c196                     NaN   
8   64060f1213c5c70c63c18b96                     NaN   
9   5d254db8bb2e30001933fe36                     NaN   
10  610cd5f2b38b2d1bffe55477                     NaN   
11  63474e67a5fd298c6103c409                     NaN   
12  5f5aa60bef062519ff711fe6                     NaN   
13  5ed856ab1f4a23368be98b1a                     NaN   
14  60f6ce6de6cf393bcde0c14d                     NaN   
15  5f4f070d58f7aa1540f27f0e                     NaN   
16  5ef1450b517aa723a13d47a9                     NaN   
17  5af5262f1b55800001f4a418                     NaN   
18  61560db6a537f0c454b23db0                     NaN   
19  610840262cce4d0594be48d0                     NaN   
20  5e86447d220e2f26a21bb066                     NaN   
21  59c9c8da5535800001a8e434                     NaN   
22  5f63a30a09bd340c84c6688d                     NaN   
23  5dd5a02b4fee995505ee89c2                     NaN   
24  60cbabd69ddfb4d7243a1e38                     NaN   
25  5f032457e2b9844beff1a2ec                     NaN   
26  6365b83b80397324720dc562                     NaN   
27  62b146e365eca239ef0dbbfb                     NaN   
28  55b2d3f2fdf99b525bc839aa                     NaN   
29  5c82c9a4d8302a00010639b8                     NaN   
30  5e872f5b3a32c337ba65aa68                     NaN   
31  558fff05fdf99b3f7aada357                     NaN   
32  61bb3a5340db417c1a138ffc                     NaN   
33  64a83272f2f581fb23f023b1                     NaN   
34  55899b8dfdf99b7ae47f5fa4                     NaN   
35  5df0932af9a01d0dabd9313d                     NaN   

          Worker ID Prolific Expt Start Time (PST)  Expt End Time (PST)  \
0   6320e37620d067c7d322246a   29/04/2023 09:55:26  29/04/2023 10:57:34   
1   63d80e0449b458dd5f8140be   29/04/2023 09:56:20  29/04/2023 11:03:30   
2   5f508a49e247cd1ff3485af3   29/04/2023 09:59:45  29/04/2023 11:02:03   
3   62827896d034545333f4610c   29/04/2023 10:09:54  29/04/2023 11:26:23   
4   5e0e1f62814bba56ea1a86dd   29/04/2023 11:49:15  29/04/2023 12:52:08   
5   5c8676deddda2d00012ad386   02/05/2023 14:27:50  02/05/2023 15:31:00   
6   6419cedec2078147e5682474   02/05/2023 14:28:03  02/05/2023 15:27:03   
7   5badcd276322c5000157c196   02/05/2023 14:28:22  02/05/2023 15:30:59   
8   64060f1213c5c70c63c18b96   02/05/2023 14:28:36  02/05/2023 15:27:56   
9   5d254db8bb2e30001933fe36   02/05/2023 14:47:06  02/05/2023 15:53:36   
10  610cd5f2b38b2d1bffe55477   02/05/2023 14:58:51  02/05/2023 16:33:58   
11  63474e67a5fd298c6103c409   02/05/2023 15:01:43  02/05/2023 16:35:21   
12  5f5aa60bef062519ff711fe6   02/05/2023 15:53:37  02/05/2023 16:55:09   
13  5ed856ab1f4a23368be98b1a   30/05/2023 10:59:04  30/05/2023 12:00:57   
14  60f6ce6de6cf393bcde0c14d   30/05/2023 11:01:32  30/05/2023 12:01:10   
15  5f4f070d58f7aa1540f27f0e   30/05/2023 11:06:00  30/05/2023 12:08:08   
16  5ef1450b517aa723a13d47a9   30/05/2023 11:06:45  30/05/2023 12:06:17   
17  5af5262f1b55800001f4a418   30/05/2023 11:12:35  30/05/2023 12:19:26   
18  61560db6a537f0c454b23db0   30/05/2023 11:19:10  30/05/2023 12:18:31   
19  610840262cce4d0594be48d0   30/05/2023 11:25:05  30/05/2023 12:40:19   
20  5e86447d220e2f26a21bb066   30/05/2023 11:25:23  30/05/2023 12:31:55   
21  59c9c8da5535800001a8e434   30/05/2023 11:28:28  30/05/2023 12:41:39   
22  5f63a30a09bd340c84c6688d   30/05/2023 11:37:57  30/05/2023 12:53:28   
23  5dd5a02b4fee995505ee89c2   30/05/2023 11:55:35  30/05/2023 13:04:58   
24  60cbabd69ddfb4d7243a1e38   31/05/2023 08:17:10  31/05/2023 

#### Print rejected subjects

In [4]:
all_df = pd.read_csv(os.path.join(preproc_folder,'complete_subs_only.csv'), index_col=0)
good_df = pd.read_csv(os.path.join(preproc_folder,'good_subs_only.csv'), index_col=0)
bad_df = all_df.iloc[~np.isin(np.array(all_df['Worker ID Prolific']), np.array(good_df['Worker ID Prolific']))]

sort_order = date_utils.argsort_dates(np.array(bad_df['Expt Start Time (PST)']))
bad_df.iloc[sort_order]

Gorilla public ID  Survey Completion Code  \
0   63f6ad3b6678834c702ed506                     NaN   
3   60c948db3f288a3058c67f98                     NaN   
11  612fd3208d3decaf3ec80bcc                     NaN   
12  63b0953847122ffebd8a5991                     NaN   
16  5d67d4393fcbbc0019f3e1a4                     NaN   
18  5a925ea389de8200013eb274                     NaN   
23  6136dfe2a772d752e49497bf                     NaN   
25  6323709c1a757febe9fae00c                     NaN   
27  5e5dba9e3d60470d71dde9ef                     NaN   
28  5fc803709e587e1295172443                     NaN   
32  633b59423091867d3a41f0f5                     NaN   
35  62904d7ade3ca9e95ae70b0a                     NaN   
39  64010f32f8dee9772983c7cd                     NaN   
41  60f71eb315abd11a590fda93                     NaN   
45  5f6e2f793c9b1032dbe72def                     NaN   
47  6118a499ea47928f81ce7b5b                     NaN   

          Worker ID Prolific Expt Start Time (PST)  Expt End Time (PST)  \
0   63f6ad3b6678834c702ed506   29/04/2023 09:52:57  29/04/2023 10:54:36   
3   60c948db3f288a3058c67f98   29/04/2023 09:58:03  29/04/2023 10:55:04   
11  612fd3208d3decaf3ec80bcc   02/05/2023 14:30:23  02/05/2023 15:48:03   
12  63b0953847122ffebd8a5991   02/05/2023 14:30:42  02/05/2023 15:41:10   
16  5d67d4393fcbbc0019f3e1a4   02/05/2023 15:36:28  02/05/2023 16:38:08   
18  5a925ea389de8200013eb274   30/05/2023 10:49:33  30/05/2023 12:11:55   
23  6136dfe2a772d752e49497bf   30/05/2023 11:12:11  30/05/2023 13:18:59   
25  6323709c1a757febe9fae00c   30/05/2023 11:16:26  30/05/2023 12:20:47   
27  5e5dba9e3d60470d71dde9ef   30/05/2023 11:21:46  30/05/2023 12:32:38   
28  5fc803709e587e1295172443   30/05/2023 11:23:15  30/05/2023 12:28:10   
32  633b59423091867d3a41f0f5   30/05/2023 11:32:55  30/05/2023 12:42:10   
35  62904d7ade3ca9e95ae70b0a   30/05/2023 12:19:54  30/05/2023 14:43:06   
39  64010f32f8dee9772983c7cd   31/05/2023 08:18:04  31/05/2023 09:29:01   
41  60f71eb315abd11a590fda93   31/05/2023 08:25:34  31/05/2023 09:42:08   
45  5f6e2f793c9b1032dbe72def   31/05/2023 09:07:20  31/05/2023 10:37:14   
47  6118a499ea47928f81ce7b5b   01/09/2023 07:51:27  01/09/2023 08:49:18   

    Total number of trials  Avg Acc  Avg RT (ms)  Experiment version num  \
0                     1000    54.30       414.40                     5.0   
3                     1000    52.90       403.60                     5.0   
11                    1000    54.80       434.00                     6.0   
12                    1000    59.33       526.56                     6.0   
16                    1000    60.50       631.00                     6.0   
18                    1000    55.60       885.80                     6.0   
23                    1000    65.00       758.56                     6.0   
25                    1000    57.20       537.00                     6.0   
27                    1000    63.20       979.20                     6.0   
28                    1000    57.50       554.80                     6.0   
32                    1000    53.90       632.20                     6.0   
35                    1000    54.40       590.90                     6.0   
39                    1000    54.00       438.30                     7.0   
41                    1000    56.10       543.70                     7.0   
45                    1000    62.00       574.70                     7.0   
47                    1000    53.50       432.50                     8.0   

    Task version num  Stim height pix  
0                2.0       150.000000  
3                2.0       185.310149  
11               6.0       150.000000  
12               6.0       159.291253  
16               6.0       150.000000  
18               6.0       150.000000  
23               6.0       209.044186  
25               6.0       150.000000  
27               6.0       150.000000  
28               6.0       150.000000  
32               6.0       150.000000  
35       

#### Print incomplete subjects

In [5]:
all_df = pd.read_csv(os.path.join(preproc_folder,'all_sub_list.csv'), index_col=0)
incomplete_df =all_df.loc[all_df['Total number of trials']<640,:]

sort_order = date_utils.argsort_dates(np.array(incomplete_df['Expt Start Time (PST)']))
incomplete_df.iloc[sort_order]

Gorilla public ID  Survey Completion Code  \
0   5ed5afc6e8229914710ada06                     NaN   
5   5f342a35aea7432daf29219d                     NaN   
15  5c935d881754ba001b25697a                     NaN   
46  631c8e97db06f601f81bd82f                     NaN   

          Worker ID Prolific Expt Start Time (PST)  Expt End Time (PST)  \
0   5ed5afc6e8229914710ada06   29/04/2023 09:39:26  29/04/2023 09:49:51   
5   5f342a35aea7432daf29219d   29/04/2023 09:55:39  29/04/2023 10:02:45   
15  5c935d881754ba001b25697a   02/05/2023 14:28:27  02/05/2023 14:40:00   
46  631c8e97db06f601f81bd82f   31/05/2023 08:18:17  31/05/2023 08:19:05   

    Total number of trials  Avg Acc  Avg RT (ms)  Experiment version num  \
0                      147     66.0        567.0                     5.0   
5                      100     59.0        463.0                     5.0   
15                     200     67.5        716.5                     6.0   
46                      13      NaN          NaN                     7.0   

    Task version num  Stim height pix  
0                2.0       171.022071  
5                2.0       150.000000  
15               6.0       193.886057  
46               7.0       187.608589