In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os, sys

sys.path.insert(0, '/user_data/mmhender/featsynth/code')

project_root = '/user_data/mmhender/featsynth/'
expt_name = 'expt5'
data_folder = os.path.join(project_root, 'online_data', expt_name)
preproc_folder = os.path.join(data_folder, 'preproc')
from utils import date_utils


In [2]:
from behav_preproc import preproc_expt5
preproc_expt5.preproc_all()

/user_data/mmhender/featsynth/online_data/expt5/data_exp_176008-v2/data_exp_176008-v2_task-sq8b.csv


/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt5.py:46: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  r = pd.read_csv(task_filename)


fixing column name for date
58d7ab1b31506e0001447859
[40 40 40 40 17  0  0  0  0  0  0  0  0  0  0  0]
60fc39cce64c39328a7c8904
[40 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
653a88110c5be0ce78adccb8
[40  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
['654b99a2dd0436b924c4298e' '657972125db865eccf249210'
 '5f33c58329beab1f63c0dfaa' '5ea2f8fc43361c22c01aaa4a'
 '6597ea83c150452ea9d580cf' '5df1a3387caa1e0c69dca179'
 '613a469755c08ab3b9d682ad' '6548fb51db60a00d76e9270b'
 '5bf01b3e2a9d2c00013ddc2a' '66153c3cc57de8108716f452'
 '657dc1eca553ae8ee187d53e' '5b6392a0105223000100fab8'
 '61687ebcd2a35ffb762d1928' '6604b1a8441e527fc9590694'
 '611cf0fcb571ffef2625d948' '5baf6705848bbd0001d6fc8a'
 '5c41f9ce4fe4f800016dfaac' '5f2448855226b0000a8129e1'
 '5db0c396ff30f700136bc805' '5ffdd8d1b2325f3c1f6edc6b'
 '5f0214e58782120a8c970fd6' '60a0b744298c64d46b63e893'
 '6135ce2a32b53777552a46b0' '655652e4d1acd4df9b343078'
 '6511f1f1490c9df9f8c7890e' '661b949e5368a2e5224c825f'
 '6505e1d7baa4d89f7a2f3b53' '650

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt5.py:449: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt5.py:453: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['pixels_per_degree'] = np.full(fill_value=ppd, \


run accuracies:
[75.  77.5 82.5 77.5 80.  85.  87.5 80.  77.5 90.  85.  85.  75.  80.
 82.5 90. ]
run avg RTs:
[841.3 776.2 785.1 797.6 764.2 755.2 808.4 747.  769.3 786.4 723.6 736.
 809.2 822.  749.3 753.8]
num missed responses:
[3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
intact acc: 0.98
final number of this subject: 7

subject 8, id: 5bf01b3e2a9d2c00013ddc2a
date = ['17/04/2024 14:45:02']
random order number: 6
run accuracies:
[80.  62.5 90.  82.5 77.5 85.  92.5 90.  90.  90.  82.5 85.  92.5 85.
 82.5 85. ]
run avg RTs:
[1053.8 1024.   970.8  905.6  903.5  821.7  921.6  804.8  804.9  817.7
  818.   816.   828.3  778.4  772.5  848.6]
num missed responses:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
intact acc: 0.98
final number of this subject: 8

subject 9, id: 66153c3cc57de8108716f452
date = ['17/04/2024 14:45:52']
random order number: 60
run accuracies:
[72.5 87.5 80.  80.  77.5 72.5 85.  80.  82.5 65.  75.  75.  85.  72.5
 87.5 77.5]
run avg RTs:
[1068.3  882.9  937.9  836.   926.4  915.6  902.   8

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt5.py:449: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt5.py:453: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['pixels_per_degree'] = np.full(fill_value=ppd, \


run accuracies:
[82.5 65.  70.  72.5 62.5 70.  80.  85.  75.  80.  65.  72.5 67.5 82.5
 82.5 80. ]
run avg RTs:
[ 992.7 1012.6  922.8  834.   860.7  833.9  852.6  777.3  806.3  750.1
  783.5  752.6  803.2  780.8  780.8  760.6]
num missed responses:
[0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0]
intact acc: 0.93
final number of this subject: 10

subject 12, id: 61687ebcd2a35ffb762d1928
date = ['17/04/2024 14:47:28']
random order number: 17
run accuracies:
[72.5 82.5 70.  80.  85.  82.5 70.  85.  80.  82.5 72.5 82.5 72.5 80.
 87.5 72.5]
run avg RTs:
[1195.8  985.1 1073.8 1054.7 1007.7  928.5  929.6  986.6  964.2  979.2
  937.1  994.2  996.6  894.9  963.   966.6]
num missed responses:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
intact acc: 0.98
final number of this subject: 11

subject 13, id: 6604b1a8441e527fc9590694
date = ['17/04/2024 14:47:32']
random order number: 22
run accuracies:
[82.5 75.  77.5 87.5 72.5 80.  70.  82.5 82.5 72.5 80.  75.  87.5 82.5
 85.  67.5]
run avg RTs:
[987.1 853.7 885.1 853.  988.

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt5.py:449: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt5.py:453: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['pixels_per_degree'] = np.full(fill_value=ppd, \


run accuracies:
[72.5 70.  77.5 75.  75.  82.5 77.5 80.  77.5 70.  85.  95.  80.  67.5
 77.5 67.5]
run avg RTs:
[1032.7  981.6  994.1  978.   964.8 1017.6  971.8 1095.8 1043.4 1092.2
 1026.4  962.6 1034.2 1026.3 1067.8 1046.4]
num missed responses:
[1 0 0 0 0 0 0 2 0 1 0 0 0 1 1 0]
intact acc: 0.99
final number of this subject: 17

subject 20, id: 5f0214e58782120a8c970fd6
date = ['17/04/2024 15:35:52']
random order number: 35
run accuracies:
[62.5 62.5 75.  65.  65.  52.5 55.  70.  50.  65.  42.5 77.5 75.  67.5
 57.5 60. ]
run avg RTs:
[979.8 953.9 960.8 963.4 948.9 987.1 968.8 953.9 923.6 911.3 779.2 942.4
 842.4 870.7 834.3 807.1]
num missed responses:
[ 1  0  1  0  3  8  9  4 11  5  2  1  1  0  2  8]
intact acc: 0.79
final number of this subject: 18

subject 21, id: 60a0b744298c64d46b63e893
date = ['17/04/2024 17:13:38']
random order number: 87
run accuracies:
[70.  75.  80.  82.5 87.5 87.5 92.5 85.  87.5 82.5 80.  85.  82.5 92.5
 80.  87.5]
run avg RTs:
[909.3 901.4 866.1 854.9 868

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt5.py:449: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt5.py:453: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['pixels_per_degree'] = np.full(fill_value=ppd, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt5.py:449: SettingWithCopyWarning: 
A value is trying to be set on a copy of a s

run accuracies:
[70.  62.5 67.5 57.5 67.5 67.5 72.5 60.  77.5 62.5 67.5 35.  65.  65.
 67.5 55. ]
run avg RTs:
[1023.3 1082.   983.   876.8 1016.1 1080.6  958.6  932.3 1103.5 1093.4
  972.3 1016.2  952.   970.6  977.6  881.7]
num missed responses:
[ 1  0  0  2  0  0  0  1  0  1  1 10  0  1  0  0]
intact acc: 0.88
final number of this subject: 20

subject 24, id: 6511f1f1490c9df9f8c7890e
date = ['18/04/2024 00:09:54']
random order number: 31
run accuracies:
[62.5 77.5 67.5 62.5 62.5 52.5 72.5 55.  65.  62.5 72.5 77.5 75.  75.
 57.5 67.5]
run avg RTs:
[ 933.6  913.2 1066.4 1059.1  999.8  992.4 1054.   949.   958.4 1143.5
  957.7  966.1 1054.1  818.9  913.4  886.2]
num missed responses:
[0 1 0 1 0 0 0 7 1 0 0 0 1 0 0 0]
intact acc: 0.89
final number of this subject: 21

subject 25, id: 661b949e5368a2e5224c825f
date = ['18/04/2024 01:16:27']
random order number: 32
run accuracies:
[57.5 70.  52.5 55.  42.5 67.5 62.5 15.  72.5 62.5 67.5 57.5 20.  55.
 75.  55. ]
run avg RTs:
[ 937.5  956.2 

#### Print good subjects

In [3]:
good_df = pd.read_csv(os.path.join(preproc_folder,'good_subs_only.csv'), index_col=0)

sort_order = date_utils.argsort_dates(np.array(good_df['Expt Start Time (PST)']))
good_df.iloc[sort_order]
good_df

Gorilla public ID        Worker ID Prolific Expt Start Time (PST)  \
0   654b99a2dd0436b924c4298e  654b99a2dd0436b924c4298e   17/04/2024 12:04:20   
1   657972125db865eccf249210  657972125db865eccf249210   17/04/2024 12:04:33   
2   5f33c58329beab1f63c0dfaa  5f33c58329beab1f63c0dfaa   17/04/2024 12:07:23   
3   6597ea83c150452ea9d580cf  6597ea83c150452ea9d580cf   17/04/2024 14:42:28   
4   5df1a3387caa1e0c69dca179  5df1a3387caa1e0c69dca179   17/04/2024 14:42:42   
5   613a469755c08ab3b9d682ad  613a469755c08ab3b9d682ad   17/04/2024 14:43:13   
6   6548fb51db60a00d76e9270b  6548fb51db60a00d76e9270b   17/04/2024 14:44:35   
7   5bf01b3e2a9d2c00013ddc2a  5bf01b3e2a9d2c00013ddc2a   17/04/2024 14:45:02   
8   66153c3cc57de8108716f452  66153c3cc57de8108716f452   17/04/2024 14:45:52   
9   5b6392a0105223000100fab8  5b6392a0105223000100fab8   17/04/2024 14:46:07   
10  61687ebcd2a35ffb762d1928  61687ebcd2a35ffb762d1928   17/04/2024 14:47:28   
11  6604b1a8441e527fc9590694  6604b1a8441e527fc9590694   17/04/2024 14:47:32   
12  611cf0fcb571ffef2625d948  611cf0fcb571ffef2625d948   17/04/2024 14:53:51   
13  5baf6705848bbd0001d6fc8a  5baf6705848bbd0001d6fc8a   17/04/2024 14:56:25   
14  5c41f9ce4fe4f800016dfaac  5c41f9ce4fe4f800016dfaac   17/04/2024 14:59:00   
15  5db0c396ff30f700136bc805  5db0c396ff30f700136bc805   17/04/2024 15:15:27   
16  5ffdd8d1b2325f3c1f6edc6b  5ffdd8d1b2325f3c1f6edc6b   17/04/2024 15:31:35   
17  5f0214e58782120a8c970fd6  5f0214e58782120a8c970fd6   17/04/2024 15:35:52   
18  60a0b744298c64d46b63e893  60a0b744298c64d46b63e893   17/04/2024 17:13:38   
19  655652e4d1acd4df9b343078  655652e4d1acd4df9b343078   17/04/2024 22:05:28   
20  6511f1f1490c9df9f8c7890e  6511f1f1490c9df9f8c7890e   18/04/2024 00:09:54   
21  6505e1d7baa4d89f7a2f3b53  6505e1d7baa4d89f7a2f3b53   18/04/2024 03:01:13   
22  6505e90a3ea83031f55ee535  6505e90a3ea83031f55ee535   18/04/2024 07:10:56   
23  6511e688100fd33b378fa688  6511e688100fd33b378fa688   18/04/2024 07:55:35   

    Expt End Time (PST)  Total number of trials  Avg Acc  Avg RT (ms)  \
0   17/04/2024 12:56:23                     640    76.69      1017.75   
1   17/04/2024 12:59:05                     640    78.81       840.38   
2   17/04/2024 12:56:34                     640    80.44       884.88   
3   17/04/2024 15:36:44                     640    77.69       780.19   
4   17/04/2024 15:58:02                     640    80.19       776.31   
5   17/04/2024 15:36:05                     640    79.00       919.31   
6   17/04/2024 15:40:06                     640    82.06       776.44   
7   17/04/2024 15:30:37                     640    84.75       868.19   
8   17/04/2024 15:32:53                     640    78.69       890.44   
9   17/04/2024 15:37:06                     640    74.75       831.62   
10  17/04/2024 15:51:17                     640    78.88       991.25   
11  17/04/2024 15:36:55                     640    79.06       874.00   
12  17/04/2024 15:49:12                     640    70.25      1026.38   
13  17/04/2024 15:52:10                     640    77.38       958.69   
14  17/04/2024 16:01:05                     640    73.50       822.62   
15  17/04/2024 16:06:07                     640    80.19       834.69   
16  17/04/2024 16:26:18                     640    77.12      1021.00   
17  17/04/2024 16:27:22                     640    62.81       914.19   
18  17/04/2024 18:03:25                     640    83.88       821.75   
19  17/04/2024 23:47:15                     640    64.00       995.06   
20  18/04/2024 02:21:26                     640    66.88       979.00   
21  18/04/2024 03:58:33                     640    69.12       817.44   
22  18/04/2024 08:01:26                     640    67.62       949.44   
23  18/04/2024 09:04:02                     640    75.25       804.12   

    Experiment version num  Task version num  Stim height pix  
0                      2.0               2.0       253.675694  
1                      2.0               2.0       210.0

#### Print rejected subjects

In [4]:
all_df = pd.read_csv(os.path.join(preproc_folder,'complete_subs_only.csv'), index_col=0)
good_df = pd.read_csv(os.path.join(preproc_folder,'good_subs_only.csv'), index_col=0)
bad_df = all_df.iloc[~np.isin(np.array(all_df['Worker ID Prolific']), np.array(good_df['Worker ID Prolific']))]

sort_order = date_utils.argsort_dates(np.array(bad_df['Expt Start Time (PST)']))
bad_df.iloc[sort_order]

Gorilla public ID        Worker ID Prolific Expt Start Time (PST)  \
3   5ea2f8fc43361c22c01aaa4a  5ea2f8fc43361c22c01aaa4a   17/04/2024 12:12:13   
10  657dc1eca553ae8ee187d53e  657dc1eca553ae8ee187d53e   17/04/2024 14:46:04   
17  5f2448855226b0000a8129e1  5f2448855226b0000a8129e1   17/04/2024 15:03:17   
22  6135ce2a32b53777552a46b0  6135ce2a32b53777552a46b0   17/04/2024 17:35:55   
25  661b949e5368a2e5224c825f  661b949e5368a2e5224c825f   18/04/2024 01:16:27   

    Expt End Time (PST)  Total number of trials  Avg Acc  Avg RT (ms)  \
3   17/04/2024 13:06:28                     640    58.73       642.60   
10  17/04/2024 15:36:56                     640    71.00       860.19   
17  17/04/2024 15:56:52                     640    59.25       885.50   
22  17/04/2024 19:27:19                     640    51.69       410.62   
25  18/04/2024 02:05:17                     640    55.62       806.56   

    Experiment version num  Task version num  Stim height pix  
3                      2.0               2.0       359.421049  
10                     2.0               2.0       210.000000  
17                     2.0               2.0       405.512985  
22                     2.0               2.0       295.522732  
25                     2.0               2.0       210.000000

#### Print incomplete subjects

In [5]:
all_df = pd.read_csv(os.path.join(preproc_folder,'all_sub_list.csv'), index_col=0)
incomplete_df =all_df.loc[all_df['Total number of trials']<640,:]

sort_order = date_utils.argsort_dates(np.array(incomplete_df['Expt Start Time (PST)']))
incomplete_df.iloc[sort_order]

Gorilla public ID        Worker ID Prolific Expt Start Time (PST)  \
4   60fc39cce64c39328a7c8904  60fc39cce64c39328a7c8904   17/04/2024 14:41:47   
8   58d7ab1b31506e0001447859  58d7ab1b31506e0001447859   17/04/2024 14:43:48   
16  653a88110c5be0ce78adccb8  653a88110c5be0ce78adccb8   17/04/2024 14:49:43   

    Expt End Time (PST)  Total number of trials  Avg Acc  Avg RT (ms)  \
4   17/04/2024 14:46:38                      65     57.0        997.0   
8   17/04/2024 14:57:02                     176     78.0       1049.0   
16  17/04/2024 14:52:28                      40     78.0        968.0   

    Experiment version num  Task version num  Stim height pix  
4                      2.0               2.0       318.375176  
8                      2.0               2.0       276.594195  
16                     2.0               2.0       210.000000