In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os, sys

sys.path.insert(0, '/user_data/mmhender/featsynth/code')

project_root = '/user_data/mmhender/featsynth/'
expt_name = 'expt4'
data_folder = os.path.join(project_root, 'online_data', expt_name)
preproc_folder = os.path.join(data_folder, 'preproc')
from utils import date_utils
from behav_preproc import preproc_expt4

In [2]:
from behav_preproc import preproc_expt4
preproc_expt4.preproc_all()

/user_data/mmhender/featsynth/online_data/expt4/data_exp_176001-v2/data_exp_176001-v2_task-sq8b.csv


/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt4.py:46: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  r = pd.read_csv(task_filename)


fixing column name for date
5ab10212fb22320001bacdfe
[24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
5c70974403f85b0001af8d5d
[70 40  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
['5fdbd87651f3a90d40e390cd' '589295bdd8cdf10001d885b2'
 '5e1ba4f4e8a6633cb7d29344' '65b29c95cbbb90f32111739b'
 '607edb9dd6541e00f4802240' '66084e0df31e23865ef3c3e3'
 '608d247fc141c8230ce3ebdc' '5967e9a831394d0001abdb3f'
 '65bc4f6759082a6190c36f50' '5f949261b23c792dafe395bc'
 '610846dd7da13e7eb86a6f39' '607728dc0b4f8590b94ae57c'
 '5ca6717bb54fe60001e22441' '5e987098f1bb6707dca13f5b'
 '5c7eb70d73dbca00011650b4' '60b7bb77c573c1a28d072811'
 '5fc65d9cc4575b0b47981de8' '5f6f25a7fb739547ff9d6206'
 '65d233b883e87f74728e655b' '5e638770b45c641082fd309f'
 '5bb2a0148f3bd70001e5633f' '613b08149aaccb2ae9fb88c6'
 '60e2ebb6ad1d5ee0e515a7c5' '65b91010b2ea4aefcdc5900e'
 '5f600669b846780f0fe45709' '65ca3273c5af74f8349914a3'
 '65bf988fde82b668f87bc037' '60f43127b2b2e32120869426'
 '61644a9055a7fdced6a7aa9c' '5fbfe145e52a44000a9c296

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt4.py:238: RuntimeWarning: Mean of empty slice
  acc = np.nanmean(run_acc).round(2)
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt4.py:239: RuntimeWarning: Mean of empty slice
  rt = np.nanmean(run_avg_rts).round(2)


saving to /user_data/mmhender/featsynth/online_data/expt4/preproc/all_sub_list.csv
saving to /user_data/mmhender/featsynth/online_data/expt4/preproc/complete_subs_only.csv

subject 0, id: 5fdbd87651f3a90d40e390cd
date = ['16/04/2024 13:22:04']
random order number: 26
run accuracies:
[77.5 75.  87.5 92.5 90.  82.5 87.5 90.  87.5 90.  85.  82.5 85.  82.5
 95.  80. ]
run avg RTs:
[1064.3  889.4  866.2  876.7  837.4  854.   816.3  856.2  810.9  827.6
  858.5  845.   878.   847.8  827.   833.3]
num missed responses:
[2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
intact acc: 0.98
final number of this subject: 1

subject 1, id: 589295bdd8cdf10001d885b2
date = ['16/04/2024 13:22:12']
random order number: 9
run accuracies:
[87.5 92.5 80.  77.5 75.  95.  87.5 75.  87.5 75.  82.5 80.  80.  77.5
 90.  95. ]
run avg RTs:
[1017.9  933.8  950.   932.7  921.6  891.8  924.   911.7  928.6  866.1
  871.4  834.2  935.6  854.4  854.   839. ]
num missed responses:
[0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0]
intact acc: 0.96
final

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt4.py:449: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt4.py:453: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['pixels_per_degree'] = np.full(fill_value=ppd, \


run accuracies:
[82.5 95.  72.5 77.5 85.  90.  85.  82.5 90.  97.5 85.  87.5 92.5 85.
 92.5 87.5]
run avg RTs:
[952.3 883.6 904.4 842.6 876.6 867.  890.7 902.6 860.9 900.6 836.3 890.3
 858.9 917.6 893.9 867.2]
num missed responses:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
intact acc: 0.98
final number of this subject: 7

subject 8, id: 65bc4f6759082a6190c36f50
date = ['17/04/2024 11:55:01']
random order number: 34
run accuracies:
[87.5 82.5 82.5 75.  77.5 85.  90.  82.5 92.5 75.  90.  77.5 87.5 87.5
 80.  80. ]
run avg RTs:
[845.  763.9 800.2 838.7 787.  831.7 752.3 779.4 736.2 768.1 724.8 772.8
 743.3 777.6 782.  819.4]
num missed responses:
[4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
intact acc: 0.98
final number of this subject: 8

subject 9, id: 5f949261b23c792dafe395bc
date = ['17/04/2024 11:55:23']
random order number: 16
run accuracies:
[82.5 92.5 90.  85.  75.  87.5 85.  85.  77.5 95.  75.  82.5 92.5 90.
 82.5 85. ]
run avg RTs:
[962.8 797.2 846.6 766.1 807.  787.4 764.8 700.8 847.9 713.7 801.2

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt4.py:449: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt4.py:453: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['pixels_per_degree'] = np.full(fill_value=ppd, \


run accuracies:
[82.5 85.  90.  67.5 85.  75.  85.  80.  87.5 70.  82.5 87.5 62.5 72.5
 87.5 82.5]
run avg RTs:
[1012.7  908.6  915.4 1015.7  872.9  833.4  896.9  874.   793.9  817.5
  782.4  882.8  846.1  835.9  826.   845.1]
num missed responses:
[0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0]
intact acc: 0.94
final number of this subject: 14

subject 16, id: 5fc65d9cc4575b0b47981de8
date = ['17/04/2024 11:57:35']
random order number: 9
run accuracies:
[80.  85.  92.5 85.  80.  97.5 85.  90.  92.5 72.5 92.5 95.  87.5 82.5
 95.  87.5]
run avg RTs:
[801.9 766.9 713.6 645.5 633.6 618.8 618.2 636.1 637.6 599.7 591.  575.3
 596.2 572.7 589.9 554.6]
num missed responses:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
intact acc: 0.93
final number of this subject: 15

subject 17, id: 5f6f25a7fb739547ff9d6206
date = ['17/04/2024 11:58:04']
random order number: 82
run accuracies:
[ 90.   85.   85.   80.   95.   85.   95.  100.   95.   92.5  92.5  90.
  90.   97.5  90.   97.5]
run avg RTs:
[ 982.1  969.9 1018.5  957.6  

#### Print good subjects

In [3]:
good_df = pd.read_csv(os.path.join(preproc_folder,'good_subs_only.csv'), index_col=0)

sort_order = date_utils.argsort_dates(np.array(good_df['Expt Start Time (PST)']))
good_df.iloc[sort_order]
good_df

Gorilla public ID        Worker ID Prolific Expt Start Time (PST)  \
0   5fdbd87651f3a90d40e390cd  5fdbd87651f3a90d40e390cd   16/04/2024 13:22:04   
1   589295bdd8cdf10001d885b2  589295bdd8cdf10001d885b2   16/04/2024 13:22:12   
2   5e1ba4f4e8a6633cb7d29344  5e1ba4f4e8a6633cb7d29344   16/04/2024 13:23:12   
3   65b29c95cbbb90f32111739b  65b29c95cbbb90f32111739b   16/04/2024 13:39:49   
4   607edb9dd6541e00f4802240  607edb9dd6541e00f4802240   16/04/2024 13:41:14   
5   608d247fc141c8230ce3ebdc  608d247fc141c8230ce3ebdc   17/04/2024 11:53:50   
6   5967e9a831394d0001abdb3f  5967e9a831394d0001abdb3f   17/04/2024 11:54:30   
7   65bc4f6759082a6190c36f50  65bc4f6759082a6190c36f50   17/04/2024 11:55:01   
8   5f949261b23c792dafe395bc  5f949261b23c792dafe395bc   17/04/2024 11:55:23   
9   610846dd7da13e7eb86a6f39  610846dd7da13e7eb86a6f39   17/04/2024 11:55:26   
10  607728dc0b4f8590b94ae57c  607728dc0b4f8590b94ae57c   17/04/2024 11:55:38   
11  5e987098f1bb6707dca13f5b  5e987098f1bb6707dca13f5b   17/04/2024 11:57:13   
12  5c7eb70d73dbca00011650b4  5c7eb70d73dbca00011650b4   17/04/2024 11:57:23   
13  60b7bb77c573c1a28d072811  60b7bb77c573c1a28d072811   17/04/2024 11:57:29   
14  5fc65d9cc4575b0b47981de8  5fc65d9cc4575b0b47981de8   17/04/2024 11:57:35   
15  5f6f25a7fb739547ff9d6206  5f6f25a7fb739547ff9d6206   17/04/2024 11:58:04   
16  65d233b883e87f74728e655b  65d233b883e87f74728e655b   17/04/2024 11:58:05   
17  5e638770b45c641082fd309f  5e638770b45c641082fd309f   17/04/2024 12:00:21   
18  5bb2a0148f3bd70001e5633f  5bb2a0148f3bd70001e5633f   17/04/2024 12:02:55   
19  613b08149aaccb2ae9fb88c6  613b08149aaccb2ae9fb88c6   17/04/2024 12:03:49   
20  60e2ebb6ad1d5ee0e515a7c5  60e2ebb6ad1d5ee0e515a7c5   17/04/2024 12:05:28   
21  65b91010b2ea4aefcdc5900e  65b91010b2ea4aefcdc5900e   17/04/2024 12:05:46   
22  5f600669b846780f0fe45709  5f600669b846780f0fe45709   17/04/2024 12:10:08   
23  65ca3273c5af74f8349914a3  65ca3273c5af74f8349914a3   17/04/2024 12:13:00   
24  65bf988fde82b668f87bc037  65bf988fde82b668f87bc037   17/04/2024 12:30:14   
25  60f43127b2b2e32120869426  60f43127b2b2e32120869426   17/04/2024 12:53:11   
26  61644a9055a7fdced6a7aa9c  61644a9055a7fdced6a7aa9c   17/04/2024 12:58:20   
27  5fbfe145e52a44000a9c2966  5fbfe145e52a44000a9c2966   17/04/2024 14:04:46   

    Expt End Time (PST)  Total number of trials  Avg Acc  Avg RT (ms)  \
0   16/04/2024 14:16:43                     640    85.88       861.69   
1   16/04/2024 14:42:52                     640    83.81       904.25   
2   16/04/2024 14:11:55                     640    80.19       797.00   
3   16/04/2024 14:26:46                     640    88.44       779.12   
4   16/04/2024 14:31:22                     640    85.31       710.25   
5   17/04/2024 12:58:16                     640    77.88       695.06   
6   17/04/2024 12:49:33                     640    87.00       884.19   
7   17/04/2024 12:42:17                     640    83.56       782.62   
8   17/04/2024 12:52:25                     640    85.38       789.50   
9   17/04/2024 12:44:52                     640    83.56       923.19   
10  17/04/2024 12:45:10                     640    84.06       837.38   
11  17/04/2024 12:46:49                     640    85.00       791.12   
12  17/04/2024 12:49:10                     640    84.94       914.81   
13  17/04/2024 12:58:44                     640    80.44       872.50   
14  17/04/2024 12:52:20                     640    87.75       634.62   
15  17/04/2024 12:47:35                     640    91.38       823.00   
16  17/04/2024 12:46:27                     640    86.75       838.88   
17  17/04/2024 12:52:42                     640    82.38       734.75   
18  17/04/2024 13:03:13                     640    83.75       912.06   
19  17/04/2024 12:54:32                     640    83.50       843.38   
20  17/04/2024 13:01:29                     640    82.25       900.38   
21  17/04/2024 13:03:40                     640    73.31       919.62   
22  17/04/2

#### Print rejected subjects

In [4]:
all_df = pd.read_csv(os.path.join(preproc_folder,'complete_subs_only.csv'), index_col=0)
good_df = pd.read_csv(os.path.join(preproc_folder,'good_subs_only.csv'), index_col=0)
bad_df = all_df.iloc[~np.isin(np.array(all_df['Worker ID Prolific']), np.array(good_df['Worker ID Prolific']))]

sort_order = date_utils.argsort_dates(np.array(bad_df['Expt Start Time (PST)']))
bad_df.iloc[sort_order]

Gorilla public ID        Worker ID Prolific Expt Start Time (PST)  \
5   66084e0df31e23865ef3c3e3  66084e0df31e23865ef3c3e3   17/04/2024 11:52:52   
12  5ca6717bb54fe60001e22441  5ca6717bb54fe60001e22441   17/04/2024 11:56:49   

    Expt End Time (PST)  Total number of trials  Avg Acc  Avg RT (ms)  \
5   17/04/2024 12:41:40                     640    73.60       857.53   
12  17/04/2024 12:49:20                     640    79.44       932.56   

    Experiment version num  Task version num  Stim height pix  
5                      2.0               8.0       362.591218  
12                     2.0               8.0       387.955020

#### Print incomplete subjects

In [5]:
all_df = pd.read_csv(os.path.join(preproc_folder,'all_sub_list.csv'), index_col=0)
incomplete_df =all_df.loc[all_df['Total number of trials']<640,:]

sort_order = date_utils.argsort_dates(np.array(incomplete_df['Expt Start Time (PST)']))
incomplete_df.iloc[sort_order]

Gorilla public ID        Worker ID Prolific Expt Start Time (PST)  \
5   5ab10212fb22320001bacdfe  5ab10212fb22320001bacdfe   17/04/2024 11:50:47   
30  5c70974403f85b0001af8d5d  5c70974403f85b0001af8d5d   17/04/2024 13:02:22   

    Expt End Time (PST)  Total number of trials  Avg Acc  Avg RT (ms)  \
5   17/04/2024 11:52:36                      24      NaN          NaN   
30  17/04/2024 13:10:41                     109     46.5        939.0   

    Experiment version num  Task version num  Stim height pix  
5                      2.0               8.0       309.360382  
30                     2.0               8.0       294.976918