In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os, sys

sys.path.append('/user_data/mmhender/featsynth/')

project_root = '/user_data/mmhender/featsynth/'
expt_name = 'pilot3'
data_folder = os.path.join(project_root, 'online_data', expt_name)
preproc_folder = os.path.join(data_folder, 'preproc')

from code_preproc import preproc_pilot3
preproc_pilot3.preproc_all()


/user_data/mmhender/featsynth/online_data/pilot3/data_exp_111471-v1/data_exp_111471-v1_task-sq8b.csv


/home/mmhender/imstat_env/lib/python3.7/site-packages/ipykernel_launcher.py:14: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  


saving to /user_data/mmhender/featsynth/online_data/pilot3/preproc/good_sub_list.csv
saving to /user_data/mmhender/featsynth/online_data/pilot3/preproc/all_sub_list.csv

subject 0, id: 1nay05m5
run accuracies, avg RTs:
[50. 52. 43. 50. 14. 54. 46. 48. 18. 14.] [223. 185. 204. 393. 262. 170. 278. 291. 392. 233.]
counterbalance cond: 1
intact acc: 0.41
skipping this subject

subject 1, id: 2q0dzuxx
run accuracies, avg RTs:
[78. 78. 86. 81. 80. 83. 83. 83. 79. 74.] [838. 742. 746. 721. 669. 685. 744. 701. 705. 536.]
counterbalance cond: 1
intact acc: 0.93

subject 2, id: 3e3nulvg
run accuracies, avg RTs:
[65. 74. 12. 53. 74. 63. 67. 72. 65. 66.] [1215.  985. 1042. 1018.  995.  999.  976. 1010.  992.  971.]
counterbalance cond: 2
intact acc: 0.64
skipping this subject

subject 3, id: gdmtbwh3
run accuracies, avg RTs:
[22. 49. 41. 45. 40. 38. 41. 36. 29. 21.] [137. 232. 234. 199. 266. 207. 164. 140. 162. 186.]
counterbalance cond: 2
intact acc: 0.37
skipping this subject

subject 4, id: j1j

#### Print complete subjects

In [2]:
good_df = pd.read_csv(os.path.join(preproc_folder,'good_sub_list.csv'))

sort_order = np.argsort(np.array(good_df['Expt Start Time (PST)']))
good_df.iloc[sort_order]
# good_df

Unnamed: 0 Gorilla public ID Survey Completion Code Worker ID mTurk  \
2           2          3e3nulvg                 nkgtdg  A1YWNRVI8ODGN5   
6           6          osbbhboc                 tuchjn  A1PBWSMSRU9YAO   
7           7          t1vwhsuy                 vithlj  A17F31TGB6QQGN   
0           0          1nay05m5                 cjxoqe  A1JL3HCA0MK9UI   
8           8          y9aprvao                 tsajiv  A2VSYXMGUH7KTY   
1           1          2q0dzuxx                 bimumx  A3QPVH0DRW0ZQV   
3           3          gdmtbwh3                 cqdhll  A1Z6SEA95MEBTN   
4           4          j1j19a92                 iqpogz  A17VFZIAVVCCSQ   
5           5          ljgs0q5d                 tptwik  A25I77AQLIIPSX   

  Expt Start Time (PST)  Expt End Time (PST)  Total number of trials  Avg Acc  \
2   13/12/2022 08:53:48  13/12/2022 09:42:01                    1000     61.1   
6   13/12/2022 08:55:33  13/12/2022 09:59:39                    1000     49.9   
7   13/12/2022 09:05:00  13/12/2022 09:54:14                    1000     43.6   
0   13/12/2022 09:09:00  13/12/2022 10:03:29                    1000     38.9   
8   13/12/2022 09:10:52  13/12/2022 09:58:34                    1000     56.9   
1   13/12/2022 09:13:58  13/12/2022 10:19:50                    1000     80.5   
3   13/12/2022 09:59:56  13/12/2022 10:54:42                    1000     36.2   
4   13/12/2022 10:00:46  13/12/2022 10:48:09                    1000     66.7   
5   13/12/2022 10:52:35  13/12/2022 11:40:41                    1000     75.4   

   Avg RT (ms)  Experiment version num  Task version num  
2       1020.3                     1.0               3.0  
6        620.5                     1.0               3.0  
7        916.1                     1.0               3.0  
0        263.1                     1.0               3.0  
8        714.9                     1.0               3.0  
1        708.7                     1.0               3.0  
3        192.7                     1.0               3.0  
4        626.7                     1.0               3.0  
5        545.0                     1.0               3.0

#### Print incomplete subjects

In [3]:
all_df = pd.read_csv(os.path.join(preproc_folder,'all_sub_list.csv'))
incomplete_df =all_df.loc[all_df['Total number of trials']<1000,:]

sort_order = np.argsort(np.array(incomplete_df['Expt Start Time (PST)']))
incomplete_df.iloc[sort_order]


Unnamed: 0 Gorilla public ID Survey Completion Code Worker ID mTurk  \
0           0          0asoorqq                    NaN  A3FBKEJRYUVH2E   
4           4          3ftv2tus                    NaN  A1VFSCIM5QRQYV   

  Expt Start Time (PST)  Expt End Time (PST)  Total number of trials  Avg Acc  \
0   13/12/2022 10:30:53  13/12/2022 10:44:54                     300    29.33   
4   13/12/2022 11:22:47  13/12/2022 12:16:36                     988    58.89   

   Avg RT (ms)  Experiment version num  Task version num  
0      1043.67                     1.0               3.0  
4      1012.11                     1.0               3.0