In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os, sys

sys.path.append('/user_data/mmhender/featsynth/')

project_root = '/user_data/mmhender/featsynth/'
expt_name = 'pilot2'
data_folder = os.path.join(project_root, 'online_data', expt_name)
preproc_folder = os.path.join(data_folder, 'preproc')

from code_preproc import preproc_pilot2
preproc_pilot2.preproc_all()


/user_data/mmhender/featsynth/online_data/pilot2/data_exp_110401-v8/data_exp_110401-v8_task-sq8b.csv


/home/mmhender/imstat_env/lib/python3.7/site-packages/ipykernel_launcher.py:14: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  


/user_data/mmhender/featsynth/online_data/pilot2/data_exp_110401-v3/data_exp_110401-v3_task-sq8b.csv
/user_data/mmhender/featsynth/online_data/pilot2/data_exp_110401-v7/data_exp_110401-v7_task-sq8b.csv


/user_data/mmhender/featsynth/code_preproc/preproc_pilot2.py:169: RuntimeWarning: Mean of empty slice
  rt = np.nanmean(run_avg_rts).round(2)


saving to /user_data/mmhender/featsynth/online_data/pilot2/preproc/good_sub_list.csv


/user_data/mmhender/featsynth/code_preproc/preproc_pilot2.py:168: RuntimeWarning: Mean of empty slice
  acc = np.nanmean(run_acc).round(2)


saving to /user_data/mmhender/featsynth/online_data/pilot2/preproc/all_sub_list.csv

subject 0, id: 1att81kl
run accuracies, avg RTs:
[61. 63. 68. 73. 68. 76. 72. 67. 66. 70.] [894. 870. 838. 921. 850. 849. 901. 885. 860. 905.]
counterbalance cond: 1
intact acc: 0.79

subject 1, id: 1mp8bn8w
run accuracies, avg RTs:
[72. 71. 74. 85. 75. 76. 71. 61. 65. 65.] [552. 593. 625. 628. 607. 610. 652. 703. 717. 706.]
counterbalance cond: 1
intact acc: 0.88

subject 2, id: 1my3gnri
run accuracies, avg RTs:
[36. 43. 46. 45. 46. 46. 39. 51. 45. 52.] [834. 217. 348. 254. 374. 384. 338. 404. 688. 618.]
counterbalance cond: 1
intact acc: 0.46
skipping this subject

subject 3, id: 42e9wdba
run accuracies, avg RTs:
[53. 48. 37. 18. 15. 41. 29. 20. 33. 38.] [1169. 1127.  881.  848. 1001.  881.  890.  894.  743.  532.]
counterbalance cond: 2
intact acc: 0.34
skipping this subject

subject 4, id: 5zaz81fs
run accuracies, avg RTs:
[48. 47. 42. 49. 47. 45. 47. 38. 42. 43.] [427. 683. 699. 621. 524. 661. 505

#### Print complete subjects

In [2]:
good_df = pd.read_csv(os.path.join(preproc_folder,'good_sub_list.csv'))

sort_order = np.argsort(np.array(good_df['Expt Start Time (PST)']))
good_df.iloc[sort_order]
# good_df

Unnamed: 0 Gorilla public ID Survey Completion Code Worker ID mTurk  \
15          15          gw4afhus                 bqwqqw             NaN   
9            9          agr6x4ss                 tbzbgl             NaN   
6            6          8s8jb2b9                 sxgyup             NaN   
3            3          42e9wdba                 glrypx             NaN   
12          12          es290hjd                 whbklr             NaN   
5            5          7zcwgrsg                 wyiqdo             NaN   
8            8          9tlhhzb7                 kveoal             NaN   
13          13          eyrsutph                 hiuxoc  A231CVHR8007FO   
10          10          cl7m00gk                 vrthhx   AC3GSBB3EWANA   
16          16          roe4s4kl                 utcdmd  A3IXRJAG3BENPO   
7            7          8ytanywi                 kcjpci   A53MOLGRRDHA4   
1            1          1mp8bn8w                 dkhvqc   ACM1CEGHXTKZP   
14          14          fe43co3j                 cggsha  A191D4AQVLECVD   
20          20          xzkbr162                 zbzyba  A3090I46GKB3N4   
2            2          1my3gnri                 qulkga  A2IHXTGWRC8SVQ   
19          19          vnzrgt2n                 jolnuj  A3QIO1R74V8U15   
11          11          ej55rcd3                 kzifdh   AJOCGRH1YM2MH   
0            0          1att81kl                 hgrfse  A2Y0VM8BAF0RMT   
18          18          ukw76mjr                 vlwpah   A50MUP8WZXFHK   
17          17          tzy6ij2n                 mwlabs  A2VOJULWLB9LYU   
4            4          5zaz81fs                 ticojv  A2SR6MOQX7KZM5   

   Expt Start Time (PST)  Expt End Time (PST)  Total number of trials  \
15   06/12/2022 18:36:07  06/12/2022 20:33:30                    1000   
9    06/12/2022 19:12:42  06/12/2022 20:01:10                    1000   
6    12/12/2022 10:57:45  12/12/2022 11:46:39                    1000   
3    12/12/2022 11:12:09  12/12/2022 11:58:49                    1000   
12   12/12/2022 11:23:52  12/12/2022 12:12:57                    1000   
5    12/12/2022 13:04:04  12/12/2022 13:51:37                    1000   
8    12/12/2022 13:17:58  12/12/2022 14:07:14                    1000   
13   12/12/2022 15:08:47  12/12/2022 15:57:29                    1000   
10   12/12/2022 15:33:14  12/12/2022 16:26:11                    1000   
16   12/12/2022 16:07:47  12/12/2022 17:02:56                    1000   
7    12/12/2022 16:25:52  12/12/2022 18:05:53                    1000   
1    12/12/2022 18:57:26  12/12/2022 19:50:32                    1000   
14   12/12/2022 19:03:31  12/12/2022 19:53:05                    1000   
20   12/12/2022 19:04:25  12/12/2022 20:35:07                    1000   
2    12/12/2022 19:05:17  12/12/2022 20:10:05                    1000   
19   12/12/2022 19:29:34  12/12/2022 20:27:43                    1000   
11   12/12/2022 19:30:33  12/12/2022 20:22:46                    1000   
0    12/12/2022 19:47:15  12/12/2022 20:38:04                    1000   
18   12/12/2022 19:48:50  12/12/2022 20:37:19                    1000   
17   12/12/2022 23:03:02  13/12/2022 00:05:20                    1000   
4    12/12/2022 23:36:02  13/12/2022 00:24:01                    1000   

    Avg Acc  Avg RT (ms)  Experiment version num  Task version num  
15     53.9       717.90                     3.0               2.0  
9      82.4       614.30                     3.0               2.0  
6      61.8      1017.00                     7.0               3.0  
3      33.2       896.60                     7.0               3.0  
12     48.9       452.70                     7.0               3.0  
5      53.7       878.80                     7.0               3.0  
8      36.0       416.50                     7.0               3.0  
13     51.8       469.40                     8.0               3.0  
10     13.5       445.20                     8.0               3.0  
16     60.4       901.40                     8.0        

#### Print incomplete subjects

In [3]:
all_df = pd.read_csv(os.path.join(preproc_folder,'all_sub_list.csv'))
incomplete_df =all_df.loc[all_df['Total number of trials']<1000,:]

sort_order = np.argsort(np.array(incomplete_df['Expt Start Time (PST)']))
incomplete_df.iloc[sort_order]


Unnamed: 0 Gorilla public ID Survey Completion Code Worker ID mTurk  \
20          20          qtlnm6fg                    NaN             NaN   
13          13          e8ubq8om                    NaN             NaN   
26          26          w1us1j7y                    NaN             NaN   
11          11          au36ln3l                    NaN             NaN   
9            9          a1yb91eq                    NaN             NaN   
19          19          in677aek                    NaN             NaN   
22          22          sw4she8d                    NaN             NaN   

   Expt Start Time (PST)  Expt End Time (PST)  Total number of trials  \
20   12/12/2022 10:56:38  12/12/2022 11:25:34                     300   
13   12/12/2022 11:11:18  12/12/2022 11:59:58                     900   
26   12/12/2022 11:28:04  12/12/2022 12:30:09                     500   
11   12/12/2022 11:28:18  12/12/2022 12:17:42                     800   
9    12/12/2022 12:09:14  12/12/2022 12:31:25                     301   
19   12/12/2022 12:34:02  12/12/2022 12:39:26                     110   
22   12/12/2022 12:42:57  12/12/2022 12:53:07                     100   

    Avg Acc  Avg RT (ms)  Experiment version num  Task version num  
20    57.00       890.00                     7.0               3.0  
13    52.56       514.33                     7.0               3.0  
26    31.40       397.60                     7.0               3.0  
11    63.75       747.25                     7.0               3.0  
9       NaN          NaN                     7.0               3.0  
19    59.00       737.00                     7.0               3.0  
22    16.00       887.00                     7.0               3.0