In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os, sys

sys.path.append('/user_data/mmhender/featsynth/')

project_root = '/user_data/mmhender/featsynth/'
expt_name = 'pilot1'
data_folder = os.path.join(project_root, 'online_data', expt_name)
preproc_folder = os.path.join(data_folder, 'preproc')

from code_preproc import preproc_pilot1
preproc_pilot1.preproc_all()


/user_data/mmhender/featsynth/online_data/pilot1/data_exp_104845-v9/data_exp_104845-v9_task-sq8b.csv
/user_data/mmhender/featsynth/online_data/pilot1/data_exp_104845-v11/data_exp_104845-v11_task-sq8b.csv
saving to /user_data/mmhender/featsynth/online_data/pilot1/preproc/good_sub_list.csv
saving to /user_data/mmhender/featsynth/online_data/pilot1/preproc/all_sub_list.csv

subject 0, id: 0yt4ywmv
run accuracies, avg RTs:
[78. 86. 78. 86. 83. 90. 92. 79. 89. 89.] [722. 713. 681. 740. 743. 700. 796. 696. 670. 717.]
counterbalance cond: 1
intact acc: 0.92

subject 1, id: 2yrs98lj
run accuracies, avg RTs:
[11. 15. 19. 31. 22. 26. 25. 15. 31. 33.] [ 574.  757.  814.  866.  770.  825.  903.  795. 1120. 1167.]
counterbalance cond: 1
intact acc: 0.24
skipping this subject

subject 2, id: 4cntwgpn
run accuracies, avg RTs:
[10. 13. 36. 22. 17.  0. 51. 11.  0. 10.] [508. 523. 452. 299. 436. 500. 307. 477. 500. 466.]
counterbalance cond: 2
intact acc: 0.15
skipping this subject

subject 3, id: 4qlnn

#### Print complete subjects

In [6]:
good_df = pd.read_csv(os.path.join(preproc_folder,'good_sub_list.csv'))

sort_order = np.argsort(np.array(good_df['Expt Start Time (PST)']))
good_df.iloc[sort_order]
# good_df

Unnamed: 0 Gorilla public ID Survey Completion Code  Worker ID mTurk  \
4           4          5ploo1az                 uxiccg              NaN   
6           6          7povpisi                 rfbsup              NaN   
2           2          4cntwgpn                 boyyad              NaN   
7           7          bw0mm82w                 poksdr              NaN   
0           0          0yt4ywmv                 qoglba              NaN   
8           8          jkjn531f                 hoispv              NaN   
9           9          msadf654                 xnsfxn              NaN   
5           5          76bhcm4d                 eshaum              NaN   
3           3          4qlnnzsd                 pczuio              NaN   
1           1          2yrs98lj                 hpkyuz              NaN   

  Expt Start Time (PST)  Expt End Time (PST)  Total number of trials  Avg Acc  \
4   02/12/2022 11:48:02  02/12/2022 12:52:59                     720     43.9   
6   02/12/2022 13:52:40  02/12/2022 14:35:23                     720     88.1   
2   02/12/2022 14:29:17  02/12/2022 15:15:38                     720     17.0   
7   02/12/2022 17:14:32  02/12/2022 17:58:18                     720     40.2   
0   18/11/2022 11:39:27  18/11/2022 12:21:38                     720     85.0   
8   22/11/2022 07:20:27  22/11/2022 08:09:25                     720     81.0   
9   22/11/2022 07:22:37  22/11/2022 08:05:29                     720     88.6   
5   22/11/2022 07:23:08  22/11/2022 08:08:00                     720     76.3   
3   22/11/2022 07:26:48  22/11/2022 08:12:11                     720     40.6   
1   22/11/2022 07:56:18  22/11/2022 08:42:07                     720     22.8   

   Avg RT (ms)  Experiment version num  Task version num  
4        644.4                    11.0              14.0  
6        819.9                    11.0              14.0  
2        446.8                    11.0              14.0  
7        335.7                    11.0              14.0  
0        717.8                     9.0              14.0  
8        646.8                     9.0              14.0  
9        546.0                     9.0              14.0  
5        625.4                     9.0              14.0  
3        269.8                     9.0              14.0  
1        859.1                     9.0              14.0

#### Print incomplete subjects

In [7]:
all_df = pd.read_csv(os.path.join(preproc_folder,'all_sub_list.csv'))
incomplete_df =all_df.loc[all_df['Total number of trials']<720,:]

sort_order = np.argsort(np.array(incomplete_df['Expt Start Time (PST)']))
incomplete_df.iloc[sort_order]


Empty DataFrame
Columns: [Unnamed: 0, Gorilla public ID, Survey Completion Code, Worker ID mTurk, Expt Start Time (PST), Expt End Time (PST), Total number of trials, Avg Acc, Avg RT (ms), Experiment version num, Task version num]
Index: []