In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os, sys

sys.path.append('/user_data/mmhender/featsynth/')

project_root = '/user_data/mmhender/featsynth/'
expt_name = 'pilot4'
data_folder = os.path.join(project_root, 'online_data', expt_name)
preproc_folder = os.path.join(data_folder, 'preproc')

from code_preproc import preproc_pilot4
preproc_pilot4.preproc_all()


/user_data/mmhender/featsynth/online_data/pilot4/data_exp_113782-v4/data_exp_113782-v4_task-sq8b.csv


/home/mmhender/imstat_env/lib/python3.7/site-packages/ipykernel_launcher.py:14: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  


saving to /user_data/mmhender/featsynth/online_data/pilot4/preproc/good_sub_list.csv
saving to /user_data/mmhender/featsynth/online_data/pilot4/preproc/all_sub_list.csv

subject 0, id: 0q0shv3m
run accuracies, avg RTs:
[68. 73. 62. 69. 65. 66. 61. 71. 64. 68.] [603. 616. 575. 576. 642. 671. 657. 635. 646. 618.]
counterbalance cond: 2
intact acc: 0.80

subject 1, id: 15owyc9p
run accuracies, avg RTs:
[64. 60. 61. 64. 65. 63. 66. 64. 55. 55.] [1014.  920. 1023. 1013.  918.  961.  903.  912.  872.  967.]
counterbalance cond: 1
intact acc: 0.73
skipping this subject

subject 2, id: 1aw5gys2
run accuracies, avg RTs:
[69. 71. 75. 73. 75. 83. 77. 71. 70. 71.] [ 836.  904. 1027.  835.  814.  882.  937.  958.  958.  900.]
counterbalance cond: 1
intact acc: 0.88

subject 3, id: 1ql190pa
run accuracies, avg RTs:
[52. 50. 44. 54. 40. 42. 35. 50. 52. 51.] [467. 523. 505. 555. 568. 468. 580. 787. 878. 779.]
counterbalance cond: 1
intact acc: 0.43
skipping this subject

subject 4, id: 2wny9ec4
run ac

#### Print complete subjects

In [2]:
good_df = pd.read_csv(os.path.join(preproc_folder,'good_sub_list.csv'))

sort_order = np.argsort(np.array(good_df['Expt Start Time (PST)']))
good_df.iloc[sort_order]
# good_df

Unnamed: 0 Gorilla public ID Survey Completion Code Worker ID mTurk  \
2            2          1aw5gys2                 fsxsiz  A2YC6PEMIRSOAA   
20          20          hiw0y77i                 qhtnfw  A3E85JBWPSBQEO   
7            7          6swid0id                 hpiimu  A256FHXGSY0E5D   
27          27          ktc83wd6                 omxdil  A3DW6KSQPG6GVQ   
14          14          btc8zumv                 lwdevd  A2APG8MSLJ6G2K   
8            8          7vtju91h                 txwlud  A2MWAXV1YRK5GH   
28          28          lbfs1h70                 tfokqe   AA4O2W236E3FW   
13          13          bpr0qdsv                 jypgnw  A3352396Q2YDRV   
19          19          gvfnxm1l                 ranbvs  A3HE8B51AK8TET   
30          30          p5dfexpc                 jaqrnh  A1KBDN6C1Q0D4U   
12          12          bhd9it6f                 cebtyb  A20UPI9DKK3X72   
1            1          15owyc9p                 wpbzbv   AND64IJKXZZMG   
32          32          qqh1odxa                 zfkkxs   AADBSWVO7D3X8   
37          37          zw6ohjae                 dujasj  A3FE4TVFPIX53P   
22          22          ibptgp2w                 svnenu  A25DP004MRTP05   
29          29          nms43bnl                 lavwcv  A2HL825K192I9Y   
4            4          2wny9ec4                 oyvshm  A2F5SKVBQQXFX0   
23          23          iuvswbcx                 ccizcs  A3KYYRZCF37KWR   
11          11          at945kvt                 wvcmht  A1FN26YO82OW51   
25          25          ixs44ht9                 fqmpid  A1G6UEWWEKUB9V   
16          16          cs36fwwf                 jimopt   AIRCO7SHVNCS2   
3            3          1ql190pa                 scplmj  A354LBXNXIKTKN   
10          10          al9pm59q                 vpsakj  A2NIZYRZHTXTM2   
21          21          i163wruc                 wriamb  A16335MOISDG1F   
15          15          cf5j8qak                 nqamgm  A2M183CETUMR96   
26          26          j5q7qpsk                 mmnvdc  A3TWLUDVUZPQ8Z   
5            5          380cpo0y                 nlposs   AMCT1XHLT5I1M   
24          24          iux5w4wx                 qeylzb   AXAO7UJYYEFCO   
0            0          0q0shv3m                 ifgqoo   AZ69TBTDH7AZS   
17          17          dlrwfrmj                 xyjhaz   AHTCV3M88WJWB   
35          35          x7gqyr98                 wbalpj  A3L1TCVTUPWKYS   
9            9          9mjm77fg                 mcskel  A2V27A9GZA1NR2   
33          33          sqrirtq7                 nsstyr  A26M997VYVK0E6   
6            6          6g49pnz7                 icvwsg   AF318MABD1U0S   
36          36          yg8nw4dz                 xwurbb   ARR9GKAG3JFE5   
31          31          p5vspv69                 dpcyzu  A2WPKP73S4MBLK   
18          18          gmbze47f                 nxufer   ARAZS0EU2QIBI   
34          34          u6ta5l81                 jpzqvz   A80OY90TZSD8F   

   Expt Start Time (PST)  Expt End Time (PST)  Total number of trials  \
2    19/01/2023 09:57:20  19/01/2023 10:59:27                    1000   
20   19/01/2023 09:58:00  19/01/2023 10:54:46                    1000   
7    19/01/2023 10:09:34  19/01/2023 11:08:23                    1000   
27   19/01/2023 10:11:11  19/01/2023 11:08:56                    1000   
14   19/01/2023 10:23:35  19/01/2023 11:22:01                    1000   
8    19/01/2023 10:24:02  19/01/2023 11:36:16                    1000   
28   19/01/2023 10:40:17  19/01/2023 11:39:56                    1000   
13   19/01/2023 12:00:15  19/01/2023 13:23:22                    1000   
19   19/01/2023 12:09:00  19/01/2023 13:44:31                    1000   
30   19/01/2023 13:06:46  19/01/2023 14:09:51                    1000   
12   21/01/2023 11:53:05  21/01/2023 12:51:00                    1000   
1    21/01/2023 11:53:53  21/01/2023 13:24:07                    1000   
32   21/01/2023 11:54:25  21/01/2023 12:56:38                    1000   
37   21/01/2023 11:54:29  21/01/2023 12:52:16           

#### Print incomplete subjects

In [3]:
all_df = pd.read_csv(os.path.join(preproc_folder,'all_sub_list.csv'))
incomplete_df =all_df.loc[all_df['Total number of trials']<1000,:]

sort_order = np.argsort(np.array(incomplete_df['Expt Start Time (PST)']))
incomplete_df.iloc[sort_order]


Unnamed: 0 Gorilla public ID Survey Completion Code Worker ID mTurk  \
35          35          ucat4e0x                    NaN  A2NAKIXS3DVGAA   

   Expt Start Time (PST)  Expt End Time (PST)  Total number of trials  \
35   19/01/2023 09:58:25  19/01/2023 10:31:00                     500   

    Avg Acc  Avg RT (ms)  Experiment version num  Task version num  
35     67.4        556.2                     4.0               1.0