In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os, sys

sys.path.insert(0, '/user_data/mmhender/featsynth/code')

project_root = '/user_data/mmhender/featsynth/'
expt_name = 'expt3'
data_folder = os.path.join(project_root, 'online_data', expt_name)
preproc_folder = os.path.join(data_folder, 'preproc')
from utils import date_utils


In [2]:
from behav_preproc import preproc_expt3
preproc_expt3.preproc_all()

/user_data/mmhender/featsynth/online_data/expt3/data_exp_143927-v4/data_exp_143927-v4_task-sq8b.csv


/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt3.py:46: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  r = pd.read_csv(task_filename)


fixing column name for date
5d1cd7cc2d5a8a00010f09ae
[40  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
6127f94d2af664941ae3bf4f
[30  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
['5f075b60ae5a1d3504e8ccb1' '6166f8f6612d8931aafbe931'
 '5f7715b6b481f41e390d2bf0' '5f78e7a0d14cd84e060fde57'
 '600df1bae8ce2f3e83838702' '5b97f2375612b30001acc4c9'
 '5eaecb0824839e59ed3523eb' '5ed8cf4782a6eb04ddf9962d'
 '597a2ec999bd880001771cb3' '5e60f63ee6385a000bcbffc9'
 '5d6e3252dfe6d10001dbe508' '5fc4bc07be970b93ac1ac3b2'
 '5f1f5fe94154031594d4e345' '60ec51c51a3158a50ded8a3e'
 '60211f150baab9043d1bc29a' '5d1a2eb176fb7d0018e8e8d6'
 '61717173748006894b2b54ff' '61017941304cf7ac38c2e110'
 '650309a7aa388e72bb5f3d22' '62db2644ab0a3a353c0dcb54']


/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt3.py:238: RuntimeWarning: Mean of empty slice
  acc = np.nanmean(run_acc).round(2)
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt3.py:239: RuntimeWarning: Mean of empty slice
  rt = np.nanmean(run_avg_rts).round(2)


saving to /user_data/mmhender/featsynth/online_data/expt3/preproc/all_sub_list.csv
saving to /user_data/mmhender/featsynth/online_data/expt3/preproc/complete_subs_only.csv

subject 0, id: 5f075b60ae5a1d3504e8ccb1
date = ['25/09/2023 05:04:31']
random order number: 6
run accuracies:
[77.5 90.  75.  60.  82.5 70.  77.5 87.5 77.5 87.5 92.5 82.5 80.  75.
 90.  80. ]
run avg RTs:
[ 818.1  796.   739.1 1019.5  734.7  761.7  792.8  903.6  707.   801.4
  833.7  826.9  788.8  811.8  821.6  882.5]
num missed responses:
[0 0 0 7 2 0 0 0 0 0 0 0 0 1 0 0]
intact acc: 0.97
final number of this subject: 1

subject 1, id: 6166f8f6612d8931aafbe931
date = ['25/09/2023 05:08:38']
random order number: 61
run accuracies:
[77.5 85.  80.  77.5 85.  82.5 92.5 87.5 80.  75.  77.5 85.  67.5 92.5
 72.5 82.5]
run avg RTs:
[848.4 875.2 866.4 859.6 820.  863.6 826.4 828.9 799.6 815.8 878.  842.5
 831.4 741.3 809.  734.6]
num missed responses:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
intact acc: 0.96
final number of this s

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt3.py:449: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt3.py:453: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['pixels_per_degree'] = np.full(fill_value=ppd, \


num missed responses:
[0 0 0 0 0 1 0 0 0 3 3 0 0 0 1 0]
intact acc: 0.95
final number of this subject: 8

subject 9, id: 5e60f63ee6385a000bcbffc9
date = ['25/09/2023 11:53:12']
random order number: 74
run accuracies:
[85.  80.  87.5 77.5 77.5 87.5 90.  82.5 85.  82.5 90.  90.  75.  92.5
 77.5 97.5]
run avg RTs:
[829.4 931.3 868.2 886.4 761.7 896.8 833.8 824.4 789.  777.4 801.3 780.4
 829.4 805.3 827.6 789.9]
num missed responses:
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
intact acc: 0.96
final number of this subject: 9

subject 10, id: 5d6e3252dfe6d10001dbe508
date = ['25/09/2023 11:56:25']
random order number: 2
run accuracies:
[72.5 90.  87.5 87.5 92.5 90.  80.  90.  90.  87.5 72.5 82.5 82.5 92.5
 85.  87.5]
run avg RTs:
[966.9 857.2 846.3 886.  850.7 789.7 909.2 803.9 889.7 814.2 863.6 750.3
 798.2 762.5 786.6 820.2]
num missed responses:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
intact acc: 0.98
final number of this subject: 10

subject 11, id: 5fc4bc07be970b93ac1ac3b2
date = ['25/09/2023 11:56:51

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt3.py:449: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt3.py:453: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['pixels_per_degree'] = np.full(fill_value=ppd, \


saving to /user_data/mmhender/featsynth/online_data/expt3/preproc/good_subs_only.csv
saving to /user_data/mmhender/featsynth/online_data/expt3/preproc/preproc_data_all.csv


#### Print good subjects

In [3]:
good_df = pd.read_csv(os.path.join(preproc_folder,'good_subs_only.csv'), index_col=0)

sort_order = date_utils.argsort_dates(np.array(good_df['Expt Start Time (PST)']))
good_df.iloc[sort_order]
good_df

Gorilla public ID        Worker ID Prolific Expt Start Time (PST)  \
0   5f075b60ae5a1d3504e8ccb1  5f075b60ae5a1d3504e8ccb1   25/09/2023 05:04:31   
1   6166f8f6612d8931aafbe931  6166f8f6612d8931aafbe931   25/09/2023 05:08:38   
2   5f7715b6b481f41e390d2bf0  5f7715b6b481f41e390d2bf0   25/09/2023 05:08:42   
3   5f78e7a0d14cd84e060fde57  5f78e7a0d14cd84e060fde57   25/09/2023 05:21:11   
4   600df1bae8ce2f3e83838702  600df1bae8ce2f3e83838702   25/09/2023 05:23:19   
5   5eaecb0824839e59ed3523eb  5eaecb0824839e59ed3523eb   25/09/2023 11:52:46   
6   5ed8cf4782a6eb04ddf9962d  5ed8cf4782a6eb04ddf9962d   25/09/2023 11:52:57   
7   597a2ec999bd880001771cb3  597a2ec999bd880001771cb3   25/09/2023 11:52:58   
8   5e60f63ee6385a000bcbffc9  5e60f63ee6385a000bcbffc9   25/09/2023 11:53:12   
9   5d6e3252dfe6d10001dbe508  5d6e3252dfe6d10001dbe508   25/09/2023 11:56:25   
10  5fc4bc07be970b93ac1ac3b2  5fc4bc07be970b93ac1ac3b2   25/09/2023 11:56:51   
11  5f1f5fe94154031594d4e345  5f1f5fe94154031594d4e345   25/09/2023 11:56:54   
12  60ec51c51a3158a50ded8a3e  60ec51c51a3158a50ded8a3e   25/09/2023 12:01:21   
13  60211f150baab9043d1bc29a  60211f150baab9043d1bc29a   25/09/2023 12:01:57   
14  5d1a2eb176fb7d0018e8e8d6  5d1a2eb176fb7d0018e8e8d6   25/09/2023 12:03:46   
15  61717173748006894b2b54ff  61717173748006894b2b54ff   25/09/2023 12:18:15   
16  61017941304cf7ac38c2e110  61017941304cf7ac38c2e110   25/09/2023 12:20:28   
17  62db2644ab0a3a353c0dcb54  62db2644ab0a3a353c0dcb54   25/09/2023 14:18:46   

    Expt End Time (PST)  Total number of trials  Avg Acc  Avg RT (ms)  \
0   25/09/2023 05:48:09                     640    80.56       815.12   
1   25/09/2023 06:01:03                     640    81.56       827.56   
2   25/09/2023 06:02:56                     640    82.25       811.62   
3   25/09/2023 06:23:31                     640    82.69      1096.31   
4   25/09/2023 06:09:08                     640    86.81       738.25   
5   25/09/2023 12:39:16                     640    87.31       825.12   
6   25/09/2023 12:38:24                     640    80.62       815.12   
7   25/09/2023 12:40:45                     640    81.25       900.62   
8   25/09/2023 12:39:41                     640    85.12       826.88   
9   25/09/2023 12:42:03                     640    85.94       837.19   
10  25/09/2023 12:48:55                     640    82.88       844.81   
11  25/09/2023 12:59:07                     640    81.56       851.94   
12  25/09/2023 12:53:56                     640    81.50       837.06   
13  25/09/2023 12:55:00                     640    80.62       824.19   
14  25/09/2023 13:14:10                     696    80.50       765.56   
15  25/09/2023 13:32:07                     640    78.25       809.56   
16  25/09/2023 13:13:46                     640    77.88      1038.56   
17  25/09/2023 15:38:12                     640    77.44       768.75   

    Experiment version num  Task version num  Stim height pix  
0                      4.0              19.0       218.817847  
1                      4.0              19.0       240.770898  
2                      4.0              19.0       321.753410  
3                      4.0              19.0       216.865220  
4                      4.0              19.0       439.006881  
5                      4.0              19.0       321.582609  
6                      4.0              19.0       324.670479  
7                      4.0              19.0       356.996245  
8                      4.0              19.0       288.630829  
9                      4.0              19.0       329.106801  
10                     4.0              19.0       352.484990  
11                     4.0              19.0       210.000000  
12                     4.0              19.0       360.860409  
13                     4.0              19.0       277.960472  
14                     4.0              19.0       459.378986  
15                     4.0              19.0       231.774501  
16            

#### Print rejected subjects

In [4]:
all_df = pd.read_csv(os.path.join(preproc_folder,'complete_subs_only.csv'), index_col=0)
good_df = pd.read_csv(os.path.join(preproc_folder,'good_subs_only.csv'), index_col=0)
bad_df = all_df.iloc[~np.isin(np.array(all_df['Worker ID Prolific']), np.array(good_df['Worker ID Prolific']))]

sort_order = date_utils.argsort_dates(np.array(bad_df['Expt Start Time (PST)']))
bad_df.iloc[sort_order]

Gorilla public ID        Worker ID Prolific Expt Start Time (PST)  \
5   5b97f2375612b30001acc4c9  5b97f2375612b30001acc4c9   25/09/2023 11:50:14   
18  650309a7aa388e72bb5f3d22  650309a7aa388e72bb5f3d22   25/09/2023 13:03:26   

    Expt End Time (PST)  Total number of trials  Avg Acc  Avg RT (ms)  \
5   25/09/2023 12:35:01                     640    84.40       735.33   
18  25/09/2023 14:14:17                     640    71.93       812.07   

    Experiment version num  Task version num  Stim height pix  
5                      4.0              19.0       306.561036  
18                     4.0              19.0       265.662726

#### Print incomplete subjects

In [5]:
all_df = pd.read_csv(os.path.join(preproc_folder,'all_sub_list.csv'), index_col=0)
incomplete_df =all_df.loc[all_df['Total number of trials']<640,:]

sort_order = date_utils.argsort_dates(np.array(incomplete_df['Expt Start Time (PST)']))
incomplete_df.iloc[sort_order]

Gorilla public ID        Worker ID Prolific Expt Start Time (PST)  \
9   5d1cd7cc2d5a8a00010f09ae  5d1cd7cc2d5a8a00010f09ae   25/09/2023 11:53:01   
20  6127f94d2af664941ae3bf4f  6127f94d2af664941ae3bf4f   25/09/2023 14:04:58   

    Expt End Time (PST)  Total number of trials  Avg Acc  Avg RT (ms)  \
9   25/09/2023 11:55:49                      40     80.0        830.0   
20  25/09/2023 14:06:50                      29      NaN          NaN   

    Experiment version num  Task version num  Stim height pix  
9                      4.0              19.0       296.873633  
20                     4.0              19.0       348.317667