In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os, sys

sys.path.insert(0, '/user_data/mmhender/featsynth/code')

project_root = '/user_data/mmhender/featsynth/'
expt_name = 'expt2'
data_folder = os.path.join(project_root, 'online_data', expt_name)
preproc_folder = os.path.join(data_folder, 'preproc')
from utils import date_utils


In [2]:
from behav_preproc import preproc_expt2
preproc_expt2.preproc_all()

/user_data/mmhender/featsynth/online_data/expt2/data_exp_130731-v8/data_exp_130731-v8_task-sq8b.csv
fixing column name for date
/user_data/mmhender/featsynth/online_data/expt2/data_exp_130731-v5/data_exp_130731-v5_task-sq8b.csv


/home/mmhender/imstat_env/lib/python3.7/site-packages/ipykernel_launcher.py:2: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  


/user_data/mmhender/featsynth/online_data/expt2/data_exp_130731-v6/data_exp_130731-v6_task-sq8b.csv
/user_data/mmhender/featsynth/online_data/expt2/data_exp_130731-v7/data_exp_130731-v7_task-sq8b.csv
5c3a518e0b5bb30001033afd
[100 100 100 100 100 100 100   0 100 100]
5c935d881754ba001b25697a
[100 100   0   0   0   0   0   0   0   0]
5ed5afc6e8229914710ada06
[100  48   0   0   0   0   0   0   0   0]
5f342a35aea7432daf29219d
[100   0   0   0   0   0   0   0   0   0]
6083a723155840ab8e6b985c
[100 100 100 100 100 100 100 100 100   0]
60f07d8c1de076bcea9e0d44
[100 100 100 100 100 100 100   0 100 100]
631c8e97db06f601f81bd82f
[13  0  0  0  0  0  0  0  0  0]
saving to /user_data/mmhender/featsynth/online_data/expt2/preproc/good_sub_list.csv


/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:217: RuntimeWarning: Mean of empty slice
  acc = np.nanmean(run_acc).round(2)
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt2.py:218: RuntimeWarning: Mean of empty slice
  rt = np.nanmean(run_avg_rts).round(2)


saving to /user_data/mmhender/featsynth/online_data/expt2/preproc/all_sub_list.csv
['63f6ad3b6678834c702ed506' '6320e37620d067c7d322246a'
 '63d80e0449b458dd5f8140be' '60c948db3f288a3058c67f98'
 '5f508a49e247cd1ff3485af3' '62827896d034545333f4610c'
 '5e0e1f62814bba56ea1a86dd' '5c8676deddda2d00012ad386'
 '6419cedec2078147e5682474' '5badcd276322c5000157c196'
 '64060f1213c5c70c63c18b96' '612fd3208d3decaf3ec80bcc'
 '63b0953847122ffebd8a5991' '5d254db8bb2e30001933fe36'
 '610cd5f2b38b2d1bffe55477' '63474e67a5fd298c6103c409'
 '5d67d4393fcbbc0019f3e1a4' '5f5aa60bef062519ff711fe6'
 '5a925ea389de8200013eb274' '5ed856ab1f4a23368be98b1a'
 '60f6ce6de6cf393bcde0c14d' '5f4f070d58f7aa1540f27f0e'
 '5ef1450b517aa723a13d47a9' '6136dfe2a772d752e49497bf'
 '5af5262f1b55800001f4a418' '6323709c1a757febe9fae00c'
 '61560db6a537f0c454b23db0' '5e5dba9e3d60470d71dde9ef'
 '5fc803709e587e1295172443' '610840262cce4d0594be48d0'
 '5e86447d220e2f26a21bb066' '59c9c8da5535800001a8e434'
 '633b59423091867d3a41f0f5' '5f63a30a

#### Print complete subjects

In [2]:
good_df = pd.read_csv(os.path.join(preproc_folder,'good_sub_list.csv'), index_col=0)

sort_order = date_utils.argsort_dates(np.array(good_df['Expt Start Time (PST)']))
good_df.iloc[sort_order]
good_df

Gorilla public ID  Survey Completion Code  \
0   63f6ad3b6678834c702ed506                     NaN   
1   6320e37620d067c7d322246a                     NaN   
2   63d80e0449b458dd5f8140be                     NaN   
3   60c948db3f288a3058c67f98                     NaN   
4   5f508a49e247cd1ff3485af3                     NaN   
5   62827896d034545333f4610c                     NaN   
6   5e0e1f62814bba56ea1a86dd                     NaN   
7   5c8676deddda2d00012ad386                     NaN   
8   6419cedec2078147e5682474                     NaN   
9   5badcd276322c5000157c196                     NaN   
10  64060f1213c5c70c63c18b96                     NaN   
11  612fd3208d3decaf3ec80bcc                     NaN   
12  63b0953847122ffebd8a5991                     NaN   
13  5d254db8bb2e30001933fe36                     NaN   
14  610cd5f2b38b2d1bffe55477                     NaN   
15  63474e67a5fd298c6103c409                     NaN   
16  5d67d4393fcbbc0019f3e1a4                     NaN   
17  5f5aa60bef062519ff711fe6                     NaN   
18  5a925ea389de8200013eb274                     NaN   
19  5ed856ab1f4a23368be98b1a                     NaN   
20  60f6ce6de6cf393bcde0c14d                     NaN   
21  5f4f070d58f7aa1540f27f0e                     NaN   
22  5ef1450b517aa723a13d47a9                     NaN   
23  6136dfe2a772d752e49497bf                     NaN   
24  5af5262f1b55800001f4a418                     NaN   
25  6323709c1a757febe9fae00c                     NaN   
26  61560db6a537f0c454b23db0                     NaN   
27  5e5dba9e3d60470d71dde9ef                     NaN   
28  5fc803709e587e1295172443                     NaN   
29  610840262cce4d0594be48d0                     NaN   
30  5e86447d220e2f26a21bb066                     NaN   
31  59c9c8da5535800001a8e434                     NaN   
32  633b59423091867d3a41f0f5                     NaN   
33  5f63a30a09bd340c84c6688d                     NaN   
34  5dd5a02b4fee995505ee89c2                     NaN   
35  62904d7ade3ca9e95ae70b0a                     NaN   
36  60cbabd69ddfb4d7243a1e38                     NaN   
37  5f032457e2b9844beff1a2ec                     NaN   
38  6365b83b80397324720dc562                     NaN   
39  64010f32f8dee9772983c7cd                     NaN   
40  62b146e365eca239ef0dbbfb                     NaN   
41  60f71eb315abd11a590fda93                     NaN   
42  55b2d3f2fdf99b525bc839aa                     NaN   
43  5c82c9a4d8302a00010639b8                     NaN   
44  5e872f5b3a32c337ba65aa68                     NaN   
45  5f6e2f793c9b1032dbe72def                     NaN   
46  558fff05fdf99b3f7aada357                     NaN   
47  6118a499ea47928f81ce7b5b                     NaN   
48  61bb3a5340db417c1a138ffc                     NaN   
49  64a83272f2f581fb23f023b1                     NaN   
50  55899b8dfdf99b7ae47f5fa4                     NaN   
51  5df0932af9a01d0dabd9313d                     NaN   

          Worker ID Prolific Expt Start Time (PST)  Expt End Time (PST)  \
0   63f6ad3b6678834c702ed506   29/04/2023 09:52:57  29/04/2023 10:54:36   
1   6320e37620d067c7d322246a   29/04/2023 09:55:26  29/04/2023 10:57:34   
2   63d80e0449b458dd5f8140be   29/04/2023 09:56:20  29/04/2023 11:03:30   
3   60c948db3f288a3058c67f98   29/04/2023 09:58:03  29/04/2023 10:55:04   
4   5f508a49e247cd1ff3485af3   29/04/2023 09:59:45  29/04/2023 11:02:03   
5   62827896d034545333f4610c   29/04/2023 10:09:54  29/04/2023 11:26:23   
6   5e0e1f62814bba56ea1a86dd   29/04/2023 11:49:15  29/04/2023 12:52:08   
7   5c8676deddda2d00012ad386   02/05/2023 14:27:50  02/05/2023 15:31:00   
8   6419cedec2078147e5682474   02/05/2023 14:28:03  02/05/2023 15:27:03   
9   5badcd276322c5000157c196   02/05/2023 14:28:22  02/05/2023 15:30:59   
10  64060f1213c5c70c63c18b96   02/05/2023 14:28:36  02/05/2023 15:27:56   
11  612fd3208d3decaf3ec80bcc   02/05/2023 14:30:23  02/05/2023 15:48:03   
12  63b0953847122ffebd8a5991   02/05/2023 14:30:42  02/05/2023 15:4

In [3]:
np.sum(np.array(good_df['Stim height pix'])==150)

20

In [4]:
np.sum(np.array(good_df['Stim height pix'])!=150)

32

#### Print incomplete subjects

In [13]:
all_df = pd.read_csv(os.path.join(preproc_folder,'all_sub_list.csv'), index_col=0)
incomplete_df =all_df.loc[all_df['Total number of trials']<1000,:]

sort_order = date_utils.argsort_dates(np.array(incomplete_df['Expt Start Time (PST)']))
incomplete_df.iloc[sort_order]

Gorilla public ID  Survey Completion Code  \
0   5ed5afc6e8229914710ada06                     NaN   
1   5c3a518e0b5bb30001033afd                     NaN   
3   6083a723155840ab8e6b985c                     NaN   
5   5f342a35aea7432daf29219d                     NaN   
10  60f07d8c1de076bcea9e0d44                     NaN   
15  5c935d881754ba001b25697a                     NaN   
46  631c8e97db06f601f81bd82f                     NaN   

          Worker ID Prolific Expt Start Time (PST)  Expt End Time (PST)  \
0   5ed5afc6e8229914710ada06   29/04/2023 09:39:26  29/04/2023 09:49:51   
1   5c3a518e0b5bb30001033afd   29/04/2023 09:51:23  29/04/2023 10:51:04   
3   6083a723155840ab8e6b985c   29/04/2023 09:55:15  29/04/2023 10:48:22   
5   5f342a35aea7432daf29219d   29/04/2023 09:55:39  29/04/2023 10:02:45   
10  60f07d8c1de076bcea9e0d44   29/04/2023 10:10:32  29/04/2023 11:42:08   
15  5c935d881754ba001b25697a   02/05/2023 14:28:27  02/05/2023 14:40:00   
46  631c8e97db06f601f81bd82f   31/05/2023 08:18:17  31/05/2023 08:19:05   

    Total number of trials  Avg Acc  Avg RT (ms)  Experiment version num  \
0                      147    66.00       567.00                     5.0   
1                      900    66.89       703.44                     5.0   
3                      900    63.44       692.44                     5.0   
5                      100    59.00       463.00                     5.0   
10                     900    65.33       784.22                     5.0   
15                     200    67.50       716.50                     6.0   
46                      13      NaN          NaN                     7.0   

    Task version num  Stim height pix  
0                2.0       171.022071  
1                2.0       183.426850  
3                2.0       218.360620  
5                2.0       150.000000  
10               2.0       251.078381  
15               6.0       193.886057  
46               7.0       187.608589