In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os, sys

sys.path.insert(0, '/user_data/mmhender/featsynth/code')

project_root = '/user_data/mmhender/featsynth/'
expt_name = 'expt3'
data_folder = os.path.join(project_root, 'online_data', expt_name)
preproc_folder = os.path.join(data_folder, 'preproc')
from utils import date_utils


In [2]:
from behav_preproc import preproc_expt3
preproc_expt3.preproc_all()

/user_data/mmhender/featsynth/online_data/expt3/data_exp_143927-v4/data_exp_143927-v4_task-sq8b.csv


/home/mmhender/imstat_env/lib/python3.7/site-packages/ipykernel_launcher.py:2: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  


fixing column name for date
5d1cd7cc2d5a8a00010f09ae
[40  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
6127f94d2af664941ae3bf4f
[30  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
saving to /user_data/mmhender/featsynth/online_data/expt3/preproc/good_sub_list.csv
saving to /user_data/mmhender/featsynth/online_data/expt3/preproc/all_sub_list.csv
['5f075b60ae5a1d3504e8ccb1' '6166f8f6612d8931aafbe931'
 '5f7715b6b481f41e390d2bf0' '5f78e7a0d14cd84e060fde57'
 '600df1bae8ce2f3e83838702' '5b97f2375612b30001acc4c9'
 '5eaecb0824839e59ed3523eb' '5ed8cf4782a6eb04ddf9962d'
 '597a2ec999bd880001771cb3' '5e60f63ee6385a000bcbffc9'
 '5d6e3252dfe6d10001dbe508' '5fc4bc07be970b93ac1ac3b2'
 '5f1f5fe94154031594d4e345' '60ec51c51a3158a50ded8a3e'
 '60211f150baab9043d1bc29a' '5d1a2eb176fb7d0018e8e8d6'
 '61717173748006894b2b54ff' '61017941304cf7ac38c2e110'
 '650309a7aa388e72bb5f3d22' '62db2644ab0a3a353c0dcb54']

subject 0, id: 5f075b60ae5a1d3504e8ccb1
date = ['25/09/2023 05:04:31']
counterbalance cond: 1
random or

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt3.py:221: RuntimeWarning: Mean of empty slice
  acc = np.nanmean(run_acc).round(2)
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt3.py:222: RuntimeWarning: Mean of empty slice
  rt = np.nanmean(run_avg_rts).round(2)


run accuracies:
[78. 90. 75. 60. 83. 70. 78. 88. 78. 88. 93. 83. 80. 75. 90. 80.]
run avg RTs:
[ 818.  796.  739. 1020.  735.  762.  793.  904.  707.  801.  834.  827.
  789.  812.  822.  883.]
intact acc: 0.97

subject 1, id: 6166f8f6612d8931aafbe931
date = ['25/09/2023 05:08:38']
counterbalance cond: 1
random order number: 61
run accuracies:
[78. 85. 80. 78. 85. 83. 93. 88. 80. 75. 78. 85. 68. 93. 73. 83.]
run avg RTs:
[848. 875. 866. 860. 820. 864. 826. 829. 800. 816. 878. 843. 831. 741.
 809. 735.]
intact acc: 0.96

subject 2, id: 5f7715b6b481f41e390d2bf0
date = ['25/09/2023 05:08:42']
counterbalance cond: 1
random order number: 79
run accuracies:
[75. 65. 85. 88. 75. 85. 93. 90. 95. 73. 93. 70. 90. 63. 88. 88.]
run avg RTs:
[874. 868. 764. 885. 822. 800. 778. 803. 728. 949. 759. 878. 748. 854.
 735. 741.]
intact acc: 0.94

subject 3, id: 5f78e7a0d14cd84e060fde57
date = ['25/09/2023 05:21:11']
counterbalance cond: 1
random order number: 84
run accuracies:
[88. 75. 65. 95. 75. 83. 7

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt3.py:418: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['which_cb'] = np.full(fill_value=which_cb, shape=[trial_data.shape[0],])
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt3.py:420: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shape=[trial_data.shape[0],])
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt3.py:424: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
T

run accuracies:
[85. 80. 88. 78. 78. 88. 90. 83. 85. 83. 90. 90. 75. 93. 78. 98.]
run avg RTs:
[829. 931. 868. 886. 762. 897. 834. 824. 789. 777. 801. 780. 829. 805.
 828. 790.]
intact acc: 0.96

subject 10, id: 5d6e3252dfe6d10001dbe508
date = ['25/09/2023 11:56:25']
counterbalance cond: 1
random order number: 2
run accuracies:
[73. 90. 88. 88. 93. 90. 80. 90. 90. 88. 73. 83. 83. 93. 85. 88.]
run avg RTs:
[967. 857. 846. 886. 851. 790. 909. 804. 890. 814. 864. 750. 798. 762.
 787. 820.]
intact acc: 0.98

subject 11, id: 5fc4bc07be970b93ac1ac3b2
date = ['25/09/2023 11:56:51']
counterbalance cond: 1
random order number: 83
run accuracies:
[93. 75. 80. 95. 70. 78. 68. 93. 83. 90. 85. 90. 73. 90. 75. 88.]
run avg RTs:
[737. 868. 862. 808. 873. 807. 907. 797. 916. 751. 814. 808. 876. 857.
 927. 909.]
intact acc: 0.99

subject 12, id: 5f1f5fe94154031594d4e345
date = ['25/09/2023 11:56:54']
counterbalance cond: 1
random order number: 20
run accuracies:
[85. 83. 60. 85. 75. 80. 68. 85. 80. 90.

#### Print complete subjects

In [3]:
good_df = pd.read_csv(os.path.join(preproc_folder,'good_sub_list.csv'), index_col=0)

sort_order = date_utils.argsort_dates(np.array(good_df['Expt Start Time (PST)']))
good_df.iloc[sort_order]
good_df

Gorilla public ID        Worker ID Prolific Expt Start Time (PST)  \
0   5f075b60ae5a1d3504e8ccb1  5f075b60ae5a1d3504e8ccb1   25/09/2023 05:04:31   
1   6166f8f6612d8931aafbe931  6166f8f6612d8931aafbe931   25/09/2023 05:08:38   
2   5f7715b6b481f41e390d2bf0  5f7715b6b481f41e390d2bf0   25/09/2023 05:08:42   
3   5f78e7a0d14cd84e060fde57  5f78e7a0d14cd84e060fde57   25/09/2023 05:21:11   
4   600df1bae8ce2f3e83838702  600df1bae8ce2f3e83838702   25/09/2023 05:23:19   
5   5b97f2375612b30001acc4c9  5b97f2375612b30001acc4c9   25/09/2023 11:50:14   
6   5eaecb0824839e59ed3523eb  5eaecb0824839e59ed3523eb   25/09/2023 11:52:46   
7   5ed8cf4782a6eb04ddf9962d  5ed8cf4782a6eb04ddf9962d   25/09/2023 11:52:57   
8   597a2ec999bd880001771cb3  597a2ec999bd880001771cb3   25/09/2023 11:52:58   
9   5e60f63ee6385a000bcbffc9  5e60f63ee6385a000bcbffc9   25/09/2023 11:53:12   
10  5d6e3252dfe6d10001dbe508  5d6e3252dfe6d10001dbe508   25/09/2023 11:56:25   
11  5fc4bc07be970b93ac1ac3b2  5fc4bc07be970b93ac1ac3b2   25/09/2023 11:56:51   
12  5f1f5fe94154031594d4e345  5f1f5fe94154031594d4e345   25/09/2023 11:56:54   
13  60ec51c51a3158a50ded8a3e  60ec51c51a3158a50ded8a3e   25/09/2023 12:01:21   
14  60211f150baab9043d1bc29a  60211f150baab9043d1bc29a   25/09/2023 12:01:57   
15  5d1a2eb176fb7d0018e8e8d6  5d1a2eb176fb7d0018e8e8d6   25/09/2023 12:03:46   
16  61717173748006894b2b54ff  61717173748006894b2b54ff   25/09/2023 12:18:15   
17  61017941304cf7ac38c2e110  61017941304cf7ac38c2e110   25/09/2023 12:20:28   
18  650309a7aa388e72bb5f3d22  650309a7aa388e72bb5f3d22   25/09/2023 13:03:26   
19  62db2644ab0a3a353c0dcb54  62db2644ab0a3a353c0dcb54   25/09/2023 14:18:46   

    Expt End Time (PST)  Total number of trials  Avg Acc  Avg RT (ms)  \
0   25/09/2023 05:48:09                     640    80.56       815.12   
1   25/09/2023 06:01:03                     640    81.56       827.56   
2   25/09/2023 06:02:56                     640    82.25       811.62   
3   25/09/2023 06:23:31                     640    82.69      1096.31   
4   25/09/2023 06:09:08                     640    86.81       738.25   
5   25/09/2023 12:35:01                     640    84.40       735.33   
6   25/09/2023 12:39:16                     640    87.31       825.12   
7   25/09/2023 12:38:24                     640    80.62       815.12   
8   25/09/2023 12:40:45                     640    81.25       900.62   
9   25/09/2023 12:39:41                     640    85.12       826.88   
10  25/09/2023 12:42:03                     640    85.94       837.19   
11  25/09/2023 12:48:55                     640    82.88       844.81   
12  25/09/2023 12:59:07                     640    81.56       851.94   
13  25/09/2023 12:53:56                     640    81.50       837.06   
14  25/09/2023 12:55:00                     640    80.62       824.19   
15  25/09/2023 13:14:10                     696    80.50       765.56   
16  25/09/2023 13:32:07                     640    78.25       809.56   
17  25/09/2023 13:13:46                     640    77.88      1038.56   
18  25/09/2023 14:14:17                     640    71.93       812.07   
19  25/09/2023 15:38:12                     640    77.44       768.75   

    Experiment version num  Task version num  Stim height pix  
0                      4.0              19.0       218.817847  
1                      4.0              19.0       240.770898  
2                      4.0              19.0       321.753410  
3                      4.0              19.0       216.865220  
4                      4.0              19.0       439.006881  
5                      4.0              19.0       306.561036  
6                      4.0              19.0       321.582609  
7                      4.0              19.0       324.670479  
8                      4.0              19.0       356.996245  
9                      4.0              19.0       288.630829  
10                     4.0              19.0       329.106801  
11                     4.0  

#### Print incomplete subjects

In [4]:
all_df = pd.read_csv(os.path.join(preproc_folder,'all_sub_list.csv'), index_col=0)
incomplete_df =all_df.loc[all_df['Total number of trials']<640,:]

sort_order = date_utils.argsort_dates(np.array(incomplete_df['Expt Start Time (PST)']))
incomplete_df.iloc[sort_order]

Gorilla public ID        Worker ID Prolific Expt Start Time (PST)  \
9   5d1cd7cc2d5a8a00010f09ae  5d1cd7cc2d5a8a00010f09ae   25/09/2023 11:53:01   
20  6127f94d2af664941ae3bf4f  6127f94d2af664941ae3bf4f   25/09/2023 14:04:58   

    Expt End Time (PST)  Total number of trials  Avg Acc  Avg RT (ms)  \
9   25/09/2023 11:55:49                      40     80.0        830.0   
20  25/09/2023 14:06:50                      29      NaN          NaN   

    Experiment version num  Task version num  Stim height pix  
9                      4.0              19.0       296.873633  
20                     4.0              19.0       348.317667