In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os, sys

# sys.path.append('/user_data/mmhender/featsynth/code')
sys.path.insert(0, '/user_data/mmhender/featsynth/code')

project_root = '/user_data/mmhender/featsynth/'
expt_name = 'expt1'
data_folder = os.path.join(project_root, 'online_data', expt_name)
preproc_folder = os.path.join(data_folder, 'preproc')

from utils import date_utils


In [2]:
import preproc_expt1
preproc_expt1.preproc_all()

/user_data/mmhender/featsynth/online_data/expt1/data_exp_118671-v7/data_exp_118671-v7_task-sq8b.csv


/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:47: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  r = pd.read_csv(task_filename)


/user_data/mmhender/featsynth/online_data/expt1/data_exp_118671-v4/data_exp_118671-v4_task-sq8b.csv


/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:47: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  r = pd.read_csv(task_filename)


/user_data/mmhender/featsynth/online_data/expt1/data_exp_118671-v6/data_exp_118671-v6_task-sq8b.csv
/user_data/mmhender/featsynth/online_data/expt1/data_exp_118671-v5/data_exp_118671-v5_task-sq8b.csv


/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:47: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  r = pd.read_csv(task_filename)


['0uup76p0' '1hq6xgij' '21wgxiso' '29qlx55e' '2ff8ctxs' '2ohedl3p'
 '2qk9bhh2' '2sl3p9be' '2z8tc4s1' '3a3u2hvp' '52ij6f3w' '6h4grx3k'
 '726i5zdz' '8lw8kd7g' 'atd6m6yh' 'aw8n6y0s' 'b995v6j3' 'bg8avnus'
 'bkhzmq6k' 'bl5hupsj' 'cwnf3q3c' 'cx0um256' 'd0hna892' 'dd2hndrz'
 'djqi501j' 'dri7bzgc' 'eoaq27re' 'fel81ofq' 'g083ik0u' 'gft9l4m9'
 'gnkd9hfq' 'h1feyx23' 'hd3vbno2' 'hv1q63xx' 'ipdbt9of' 'ly7z1qvo'
 'mas2t6lw' 'mucuak8m' 'n5h0uimz' 'oi7uauwe' 'oopgcjc1' 'oyn424vt'
 'pdleyfxl' 'pt3rwv2j' 'pyqt5mp6' 'q38k0ojb' 'r338tjmq' 't3bqc4m0'
 'tl171pdv' 'ttjpkfir' 'v2egvozi' 'vx6p48kn' 'w3m3u3sf' 'wgakft4x'
 'wsdy4zta' 'x0viplja' 'x5du0za5' 'xdxj2p7s' 'xj8o4lb8' 'y60p7t9a'
 'ynwf87n8']


/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:228: RuntimeWarning: Mean of empty slice
  acc = np.nanmean(run_acc).round(2)
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:229: RuntimeWarning: Mean of empty slice
  rt = np.nanmean(run_avg_rts).round(2)


saving to /user_data/mmhender/featsynth/online_data/expt1/preproc/all_sub_list.csv
saving to /user_data/mmhender/featsynth/online_data/expt1/preproc/complete_subs_only.csv

subject 0, id: 0uup76p0
date = ['23/03/2023 05:42:05']
counterbalance cond: 1
random order number: 11
run accuracies:
[84. 83. 90. 84. 83. 82. 86. 88. 82. 87.]
run avg RTs:
[629.7 564.9 568.1 532.4 586.3 535.2 554.5 531.6 561.8 549.1]
num missed responses:
[0 0 0 0 0 0 0 0 0 0]
intact acc: 0.97
final number of this subject: 1

subject 1, id: 1hq6xgij
date = ['14/03/2023 08:09:10']
counterbalance cond: 1
random order number: 99
run accuracies:
[69. 70. 68. 71. 68. 76. 74. 84. 80. 81.]
run avg RTs:
[1115.3 1060.4  998.4 1021.5  936.9  897.1  930.3  903.2  849.7  862.2]
num missed responses:
[0 0 1 0 1 0 0 0 0 0]
intact acc: 0.90
final number of this subject: 2

subject 2, id: 21wgxiso
date = ['09/03/2023 14:06:25']
counterbalance cond: 1
random order number: 34
run accuracies:
[71. 73. 70. 78. 72. 80. 70. 70. 77. 72.]

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:429: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['which_cb'] = np.full(fill_value=which_cb, shape=[trial_data.shape[0],])
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:430: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:434: SettingWithCopyWarning: 
A value is trying to

run accuracies:
[59. 77. 78. 68. 69. 78. 72. 72. 80. 75.]
run avg RTs:
[617.6 772.3 727.6 650.7 611.5 691.2 737.7 714.3 653.2 645.9]
num missed responses:
[0 0 0 3 0 0 0 1 0 1]
intact acc: 0.93
final number of this subject: 5

subject 6, id: 2qk9bhh2
date = ['09/03/2023 10:35:04']
counterbalance cond: 1
random order number: 43
run accuracies:
[70. 59. 67. 58. 63. 61. 63. 65. 52. 70.]
run avg RTs:
[ 996.4  961.3  887.1  941.1 1045.5  898.2  914.2 1045.1  938.7  924.1]
num missed responses:
[ 1  1  2  0  4  0  1  4 13  0]
intact acc: 0.66
intact accuracy too low, skipping subject

subject 7, id: 2sl3p9be
date = ['14/03/2023 08:17:29']
counterbalance cond: 1
random order number: 18
run accuracies:
[63. 82. 71. 83. 83. 78. 77. 81. 78. 67.]
run avg RTs:
[560.4 655.4 630.6 602.8 594.5 650.1 627.9 574.1 578.8 586.8]
num missed responses:
[0 0 0 0 0 0 0 0 0 0]
intact acc: 0.92
final number of this subject: 6

subject 8, id: 2z8tc4s1
date = ['09/02/2023 11:51:29']
counterbalance cond: 1
random 

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:429: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['which_cb'] = np.full(fill_value=which_cb, shape=[trial_data.shape[0],])
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:430: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:434: SettingWithCopyWarning: 
A value is trying to


subject 15, id: aw8n6y0s
date = ['24/03/2023 05:32:04']
counterbalance cond: 2
random order number: 29
run accuracies:
[66. 72. 66. 75. 72. 68. 70. 75. 78. 69.]
run avg RTs:
[902.7 794.4 764.3 794.9 733.4 811.  836.7 873.3 823.1 770.4]
num missed responses:
[0 1 0 0 0 0 1 0 0 0]
intact acc: 0.87
final number of this subject: 12

subject 16, id: b995v6j3
date = ['09/03/2023 10:03:29']
counterbalance cond: 2
random order number: 71
run accuracies:
[69. 72. 80. 82. 78. 78. 74. 82. 85. 91.]
run avg RTs:
[669.6 750.8 688.3 682.6 700.1 680.3 671.8 625.2 621.2 609.8]
num missed responses:
[0 0 0 0 0 0 0 0 1 0]
intact acc: 0.94
final number of this subject: 13

subject 17, id: bg8avnus
date = ['22/03/2023 17:44:25']
counterbalance cond: 1
random order number: 36
run accuracies:
[74. 80. 86. 79. 80. 80. 86. 83. 86. 83.]
run avg RTs:
[754.5 833.4 746.2 765.5 700.3 753.5 777.6 805.5 793.1 771. ]
num missed responses:
[0 0 0 0 0 0 0 0 1 0]
intact acc: 0.95
final number of this subject: 14

subjec

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:429: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['which_cb'] = np.full(fill_value=which_cb, shape=[trial_data.shape[0],])
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:430: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:434: SettingWithCopyWarning: 
A value is trying to


subject 21, id: cx0um256
date = ['23/03/2023 02:30:41']
counterbalance cond: 2
random order number: 13
run accuracies:
[64. 76. 81. 80. 69. 67. 72. 75. 76. 77.]
run avg RTs:
[586.2 838.3 758.2 752.8 794.9 796.2 728.2 674.1 711.2 760.6]
num missed responses:
[0 0 0 0 0 0 0 0 0 0]
intact acc: 0.93
final number of this subject: 17

subject 22, id: d0hna892
date = ['09/03/2023 10:28:29']
counterbalance cond: 2
random order number: 4
run accuracies:
[73. 66. 64. 75. 60. 72. 72. 64. 78. 71.]
run avg RTs:
[738.5 802.2 794.2 727.2 679.1 662.  665.1 648.8 696.1 745.4]
num missed responses:
[0 1 0 0 2 0 1 1 1 0]
intact acc: 0.82
final number of this subject: 18

subject 23, id: dd2hndrz
date = ['14/03/2023 08:08:10']
counterbalance cond: 1
random order number: 82
run accuracies:
[79. 76. 79. 75. 81. 86. 80. 82. 77. 77.]
run avg RTs:
[936.3 976.3 959.4 917.7 986.8 951.7 926.7 864.5 722.8 772.5]
num missed responses:
[0 0 0 0 0 0 0 0 0 0]
intact acc: 0.95
final number of this subject: 19

subject

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:429: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['which_cb'] = np.full(fill_value=which_cb, shape=[trial_data.shape[0],])
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:430: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:434: SettingWithCopyWarning: 
A value is trying to

run accuracies:
[70. 69. 69. 57. 61. 66. 68. 54. 73. 49.]
run avg RTs:
[1011.2  913.8  582.2  524.6  607.6  560.6  517.5  489.6  623.6  601.6]
num missed responses:
[ 0  2  0  2  0  1  0  0  0 35]
intact acc: 0.80
final number of this subject: 25

subject 34, id: ipdbt9of
date = ['23/02/2023 09:42:07']
counterbalance cond: 1
random order number: 7
run accuracies:
[78. 81. 74. 75. 79. 75. 79. 76. 77. 75.]
run avg RTs:
[ 910.7 1028.5 1032.7  967.2 1036.5  963.7  879.7  920.2  938.3  907.8]
num missed responses:
[0 0 0 0 0 0 0 0 0 0]
intact acc: 0.92
final number of this subject: 26

subject 35, id: ly7z1qvo
date = ['27/03/2023 13:58:27']
counterbalance cond: 2
random order number: 36
run accuracies:
[74. 81. 88. 79. 87. 78. 82. 79. 76. 85.]
run avg RTs:
[766.1 745.8 782.8 753.2 705.3 629.7 671.  642.  602.4 620.3]
num missed responses:
[0 0 0 0 0 0 0 0 0 0]
intact acc: 0.95
final number of this subject: 27

subject 36, id: mas2t6lw
date = ['14/03/2023 08:10:29']
counterbalance cond: 1
ra

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:429: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['which_cb'] = np.full(fill_value=which_cb, shape=[trial_data.shape[0],])
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:430: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:434: SettingWithCopyWarning: 
A value is trying to


subject 41, id: oyn424vt
date = ['14/03/2023 10:05:21']
counterbalance cond: 2
random order number: 98
run accuracies:
[70. 77. 72. 69. 77. 67. 67. 75. 65. 69.]
run avg RTs:
[918.6 769.2 739.8 850.2 688.8 618.2 660.4 658.2 624.2 673.8]
num missed responses:
[1 0 0 1 1 0 1 0 3 0]
intact acc: 0.85
final number of this subject: 31

subject 42, id: pdleyfxl
date = ['27/03/2023 01:18:57']
counterbalance cond: 2
random order number: 14
run accuracies:
[66. 53. 64. 72. 56. 63. 79. 69. 72. 65.]
run avg RTs:
[556.8 528.6 544.3 528.3 539.6 504.  515.3 518.5 532.6 546. ]
num missed responses:
[0 0 0 0 0 0 0 0 0 0]
intact acc: 0.78
final number of this subject: 32

subject 43, id: pt3rwv2j
date = ['09/02/2023 13:41:46']
counterbalance cond: 2
random order number: 77
run accuracies:
[70. 71. 76. 63. 74. 72. 64. 70. 67. 63.]
run avg RTs:
[712.2 748.6 726.2 718.  747.8 744.8 720.1 637.2 614.3 638.8]
num missed responses:
[0 0 0 0 0 0 0 0 0 0]
intact acc: 0.86
final number of this subject: 33

subjec

/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:429: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['which_cb'] = np.full(fill_value=which_cb, shape=[trial_data.shape[0],])
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:430: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trial_data['random_order_number'] = np.full(fill_value=random_order_number, \
/user_data/mmhender/featsynth/code/behav_preproc/preproc_expt1.py:434: SettingWithCopyWarning: 
A value is trying to


subject 58, id: xj8o4lb8
date = ['09/02/2023 16:22:00']
counterbalance cond: 1
random order number: 4
run accuracies:
[43. 34. 37. 56. 33. 38. 36. 38. 31. 40.]
run avg RTs:
[907.5 681.7 800.3 919.4 760.3 881.  998.7 816.3 911.4 757.7]
num missed responses:
[18 26 22  6 31 22 25 27 29 27]
intact acc: 0.45
intact accuracy too low, skipping subject

subject 59, id: y60p7t9a
date = ['24/03/2023 09:59:15']
counterbalance cond: 1
random order number: 18
run accuracies:
[58. 72. 65. 70. 73. 51. 62. 64. 65. 54.]
run avg RTs:
[764.1 681.7 663.8 706.7 678.3 702.7 805.1 593.5 541.  547.2]
num missed responses:
[0 0 0 0 0 0 6 0 0 1]
intact acc: 0.82
final number of this subject: 44

subject 60, id: ynwf87n8
date = ['23/03/2023 09:23:14']
counterbalance cond: 1
random order number: 90
run accuracies:
[63. 67. 82. 72. 64. 62. 66. 70. 71. 76.]
run avg RTs:
[1014.5  693.2  703.1  727.1  842.7  689.1  668.1  734.3  652.5  684.2]
num missed responses:
[6 1 0 0 0 0 0 4 0 0]
intact acc: 0.81
final number

#### Print good subjects

In [3]:
good_df = pd.read_csv(os.path.join(preproc_folder,'good_subs_only.csv'), index_col=0)

sort_order = date_utils.argsort_dates(np.array(good_df['Expt Start Time (PST)']))
good_df.iloc[sort_order]
good_df

Gorilla public ID Survey Completion Code Worker ID mTurk  \
0           0uup76p0                 utmeoo  A1TMZLYXQAK8Q0   
1           1hq6xgij                 yxgdmf  A2A6FH0F7LD9ND   
2           21wgxiso                 fatmgq  A230VUDYOCRZ4N   
3           2ff8ctxs                 hawups  A18E16UFE351U6   
4           2ohedl3p                 ugvfpb  A320QA9HJFUOZO   
5           2sl3p9be                 cxwxfk  A19ZWBQT8A3LIR   
6           2z8tc4s1                 hnivjf  A2FB5UQTR3E0NX   
7           52ij6f3w                 ozklsg   AN97L0D8U31MS   
8           6h4grx3k                 jixbqf  A3DF3331GOTRJP   
9           726i5zdz                 pigmbi  A1TARNH07A75CG   
10          atd6m6yh                 sjhabg  A2196WCNDZULFS   
11          aw8n6y0s                 nshohl  A3PTO0DMF57GDG   
12          b995v6j3                 rkcmvp  A1NKBXOTZAI1YK   
13          bg8avnus                 jjsumx  A3QPVH0DRW0ZQV   
14          bkhzmq6k                 eniuxk   APGX2WZ59OWDN   
15          bl5hupsj                 abwnvt  A1POQWMOWKNQCN   
16          cx0um256                 pbxmqh  A28HB7240OFGEW   
17          d0hna892                 xuxqyh  A2RBF3IIJP15IH   
18          dd2hndrz                 wfnzpr    ANFWGSQ8BQRZ   
19          djqi501j                 bccocc  A3PLJHXXSLPL0X   
20          dri7bzgc                 bejpur  A3RCX3IQ8L6HHW   
21          eoaq27re                 txlypp  A1TMZLYXQAK8Q0   
22          fel81ofq                 tiggii  A3D2U4QF7821ZW   
23          gft9l4m9                 gajbqh  A2VR9O234UCT9T   
24          hv1q63xx                 vjhfew  A3RVHUY67SVXQV   
25          ipdbt9of                 iavmyx  A2541C8MY0BYV3   
26          ly7z1qvo                 njzlsq  A3RQN5RZD1N2KP   
27          mucuak8m                 vgbtgt   AVIEE6LDH0BT5   
28          n5h0uimz                 bbursa  A2MCG5W6LHSRG9   
29          oi7uauwe                 ubsste  A3QPVH0DRW0ZQV   
30          oyn424vt                 qxdxsj   AEMQTBRPPWJTC   
31          pdleyfxl                 wlonju  A1POQWMOWKNQCN   
32          pt3rwv2j                 xfgdgj  A3JI3B5GTVA95F   
33          pyqt5mp6                 jsbsxh  A2B93NS1ZZ7QD7   
34          q38k0ojb                 sytnvp  A2ONILC0LZKG6Y   
35          r338tjmq                 qruiuz  A1TARNH07A75CG   
36          tl171pdv                 oxlftx  A3INEKAD86IRQC   
37          v2egvozi                 mazskv  A33B85TN97HQ33   
38          vx6p48kn                 danror  A2GTJ0BD4CG1A2   
39          w3m3u3sf                 bjetdp  A166A2M31CW2C7   
40          wsdy4zta                 uqcggl  A3PTO0DMF57GDG   
41          x0viplja                 qlgwth   A9LSEP71DNP4O   
42          xdxj2p7s                 jicljy  A37JC45Y9GLSA7   
43          y60p7t9a                 qobchj  A2K7RVHQRCM91M   
44          ynwf87n8                 jukrfu  A1DCKRRPA4AWVD   

   Expt Start Time (PST)  Expt End Time (PST)  Total number of trials  \
0    23/03/2023 05:42:05  23/03/2023 06:51:59                    1000   
1    14/03/2023 08:09:10  14/03/2023 09:16:04                    1000   
2    09/03/2023 14:06:25  09/03/2023 15:08:18                    1000   
3    23/02/2023 13:13:51  23/02/2023 14:18:35                    1000   
4    23/02/2023 09:50:26  23/02/2023 11:15:40                    1000   
5    14/03/2023 08:17:29  14/03/2023 09:18:10                    1000   
6    09/02/2023 11:51:29  09/02/2023 13:39:44                    1000   
7    22/03/2023 15:49:50  22/03/2023 16:50:21                    1000   
8    27/03/2023 21:06:58  27/03/2023 22:30:11                    1000   
9    28/03/2023 06:15:07  28/03/2023 07:43:04                    1000   
10   09/03/2023 10:19:18  09/03/2023 11:20:14                    1000   
11   24/03/2023 05:32:04  24/03/2023 06:31:54                    1000   
12   09/03/2023 10:03:29  09/03/2023 11:29:06                    1000   
13   22/03/2023 17:44:25  22/03/2023 18:57:09                    1000   
14   23/0

#### Print rejected subjects

In [4]:
all_df = pd.read_csv(os.path.join(preproc_folder,'complete_subs_only.csv'), index_col=0)
good_df = pd.read_csv(os.path.join(preproc_folder,'good_subs_only.csv'), index_col=0)
bad_df = all_df.iloc[~np.isin(np.array(all_df['Worker ID mTurk']), np.array(good_df['Worker ID mTurk']))]

sort_order = date_utils.argsort_dates(np.array(bad_df['Expt Start Time (PST)']))
bad_df.iloc[sort_order]

Gorilla public ID Survey Completion Code Worker ID mTurk  \
30          gnkd9hfq                 fjkrpb   A6GXI3YR6FBW8   
9           3a3u2hvp                 ndncbd  A3QLH68D89SJ4J   
58          xj8o4lb8                 lzyadu  A2PAXZMD7Q7NKH   
13          8lw8kd7g                 xmbuyg  A2NEATATGTMKMN   
3           29qlx55e                 kqbxsn  A1JL3HCA0MK9UI   
28          g083ik0u                 vqmnix  A1QF3RIVN7Y73Q   
6           2qk9bhh2                 pmskre  A1YWNRVI8ODGN5   
53          wgakft4x                 vvficy  A1VFSCIM5QRQYV   
49          ttjpkfir                 oabahr  A3QIO1R74V8U15   
47          t3bqc4m0                 edzvtd   AC3GSBB3EWANA   
36          mas2t6lw                 cwyvct  A1T579QEGUZKIP   
20          cwnf3q3c                 xqgpkp  A1T579QEGUZKIP   
31          h1feyx23                 aotrtj   AC3GSBB3EWANA   
32          hd3vbno2                 txtliq  A2AAFWAAS9C1QC   

   Expt Start Time (PST)  Expt End Time (PST)  Total number of trials  \
30   09/02/2023 11:56:34  09/02/2023 13:01:39                    1000   
9    09/02/2023 12:28:19  09/02/2023 13:34:42                    1000   
58   09/02/2023 16:22:00  09/02/2023 17:21:06                    1000   
13   23/02/2023 10:11:52  23/02/2023 11:22:17                    1000   
3    23/02/2023 11:59:44  23/02/2023 13:31:29                    1000   
28   09/03/2023 10:11:00  09/03/2023 11:35:18                    1000   
6    09/03/2023 10:35:04  09/03/2023 11:37:27                    1000   
53   09/03/2023 14:04:50  09/03/2023 15:10:48                    1000   
49   09/03/2023 14:29:36  09/03/2023 15:42:27                    1000   
47   14/03/2023 08:05:02  14/03/2023 09:04:33                    1000   
36   14/03/2023 08:10:29  14/03/2023 09:35:34                    1000   
20   22/03/2023 17:42:38  22/03/2023 19:32:17                    1000   
31   22/03/2023 19:10:17  22/03/2023 20:17:24                    1000   
32   28/03/2023 06:22:03  28/03/2023 07:33:53                    1000   

    Avg Acc  Avg RT (ms)  Experiment version num  Task version num  \
30     47.0       950.10                     4.0               9.0   
9      43.9       766.80                     4.0               9.0   
58     38.6       843.40                     4.0               9.0   
13     35.4       349.30                     5.0              10.0   
3      23.0       287.50                     5.0              10.0   
28     55.6       522.30                     5.0              10.0   
6      62.8       955.10                     5.0              10.0   
53     58.3       870.80                     5.0              10.0   
49      0.3       546.00                     5.0              10.0   
47     37.0       824.10                     7.0              10.0   
36     59.7      1029.00                     7.0              10.0   
20     50.6       734.67                     7.0              10.0   
31     18.3       898.14                     7.0              10.0   
32     76.8       682.30                     7.0              10.0   

    Stim height pix  
30        67.468810  
9         26.295302  
58       114.551327  
13       150.000000  
3        243.108156  
28       231.712395  
6        150.000000  
53       150.000000  
49       159.031770  
47       155.120798  
36       150.000000  
20       150.000000  
31       158.392494  
32       194.062319

#### Print incomplete subjects

In [5]:
all_df = pd.read_csv(os.path.join(preproc_folder,'all_sub_list.csv'), index_col=0)
incomplete_df =all_df.loc[all_df['Total number of trials']<640,:]

sort_order = date_utils.argsort_dates(np.array(incomplete_df['Expt Start Time (PST)']))
incomplete_df.iloc[sort_order]

Gorilla public ID Survey Completion Code Worker ID mTurk  \
31           bxip5iyn                    NaN  A3PQ4TK5CDFQKO   
64           lfyxzou9                    NaN  A3HNEYFOIJWPH1   
42           djxlin7t                    NaN  A2KMX4HGXSWS7U   
89           teti0yq6                    NaN  A3GK90X2QOFR53   
61           ivwzuwoe                    NaN   A98E8M4QLI9RS   
23           8zmdddn1                    NaN   A4T4577P6JL6R   
32           ca4ipz1r                    NaN  A2Z6NL0CTXY0ZB   
17           6pzxdx2u                    NaN  A1PAY3X73PQ16S   
79           pdz1iu7z                    NaN  A3D2U4QF7821ZW   
77           p2b097nc                    NaN  A2OO4PG3LBLP5I   
55           grjflqp9                    NaN  A21UA6O7ZFAIQJ   
72           o8nkccb9                    NaN   AQXRHIMQ7UK7O   
38           d1veud6o                    NaN  A1T579QEGUZKIP   
20           7v5eyrqm                    NaN  A1T579QEGUZKIP   
104          xgxqbos5                    NaN   AVIEE6LDH0BT5   
94           v37nmohd                    NaN  A3L0DCUXI7X3A9   
39           dcfky6xw                    NaN  A3090I46GKB3N4   
67           m8zjsx0c                    NaN  A2EI075XZT9Y2S   
5            2c7ai2y6                    NaN   AD1ILDUXZHASF   
71           o2medb30                    NaN  A3O81LHBBI8NPK   
76           p216j9ye                    NaN  A25I77AQLIIPSX   
34           cqudjfd5                    NaN  A1XAOEDK0Y2KBT   
57           h225qu5b                    NaN   AD1ILDUXZHASF   
12           3opo97kq                    NaN   AAERXGOW20AKP   
44           dudzeud2                    NaN  A3L60SOWLYEDN2   
15           53s54ego                    NaN   ATHS9GUME1XCA   
33           coz37iw3                    NaN  A2SUZSTVMRH4TQ   
92           v1q90i95                    NaN  A2ZUCKYJE4DPV7   
65           loilx3d3                    NaN  A3FLM6270J9GVH   
49           epavtpns                    NaN   A2YVQKJX3FO6P   
24           9l8h5n69                    NaN     ATAF6F062DH   
21           81lplq56                    NaN  A3843S9LWPDN2K   

    Expt Start Time (PST)  Expt End Time (PST)  Total number of trials  \
31    09/02/2023 11:58:03  09/02/2023 12:22:52                     400   
64    23/02/2023 10:50:22  23/02/2023 11:03:48                     200   
42    23/02/2023 12:43:05  23/02/2023 12:51:22                     100   
89    23/02/2023 13:31:31  23/02/2023 14:58:45                     412   
61    09/03/2023 10:08:58  09/03/2023 10:21:36                     200   
23    09/03/2023 10:17:46  09/03/2023 10:23:56                     100   
32    09/03/2023 10:43:25  09/03/2023 11:05:12                     200   
17    09/03/2023 11:17:53  09/03/2023 11:36:05                     300   
79    09/03/2023 11:22:32  09/03/2023 11:28:09                     100   
77    09/03/2023 11:50:13  09/03/2023 12:45:53                     200   
55    09/03/2023 12:05:11  09/03/2023 12:54:34                     600   
72    09/03/2023 12:18:14  09/03/2023 12:56:00                     200   
38    09/03/2023 12:21:18  09/03/2023 13:07:04                     500   
20    09/03/2023 13:22:46  09/03/2023 13:28:19                     100   
104   14/03/2023 08:02:55  14/03/2023 08:31:52                     500   
94    14/03/2023 08:03:56  14/03/2023 08:09:47                     100   
39    14/03/2023 08:17:35  14/03/2023 08:34:37                     200   
67    14/03/2023 10:54:43  14/03/2023 10:54:58                       3   
5     14/03/2023 14:11:13  14/03/2023 14:17:49                     102   
71    21/03/2023 05:37:12  21/03/2023 05:37:39                       5   
76    21/03/2023 06:41:35  21/03/2023 06:45:50                      76   
34    22/03/2023 18:48:59  22/03/2023 18:53:52                      88   
57    22/03/2023 19:40:04  22/03/2023 19:40:22                       4   
12    23/03/2023 00:16:23  23/03/2023 00:22:05                     100   
44    23/03/2023 07:18:15  23/03/2023 07: